export type TechCategory =
  | "frontend"
  | "backend"
  | "database"
  | "cloud"
  | "devops"
  | "ai"
  | "tooling"
  | "storage"
  | "compute"
  | "auth"
  | "payment"
  | "automation"
  | "messaging"
  | "search"
  | "monitoring"
  | "cicd"
  | "security"
  | "testing"
  | "vector-db"
  | "aws"
  | "gcp";

export interface TechItem {
  id: string;
  label: string;
  icon: string;
  category: TechCategory;
  defaultType?: string;
}

export const TECH_ECOSYSTEM: TechItem[] = [
  // ==================== FRONTEND ====================
  {
    id: "react",
    label: "React",
    icon: "logos:react",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "vue",
    label: "Vue.js",
    icon: "logos:vue",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "angular",
    label: "Angular",
    icon: "logos:angular-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "svelte",
    label: "Svelte",
    icon: "logos:svelte-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "nextjs",
    label: "Next.js",
    icon: "logos:nextjs-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "nuxt",
    label: "Nuxt.js",
    icon: "logos:nuxt-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "remix",
    label: "Remix",
    icon: "logos:remix-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "sveltekit",
    label: "SvelteKit",
    icon: "logos:svelte-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "astro",
    label: "Astro",
    icon: "logos:astro",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "vite",
    label: "Vite",
    icon: "logos:vitejs",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "flutter",
    label: "Flutter",
    icon: "logos:flutter",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "react-native",
    label: "React Native",
    icon: "logos:react",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "swift",
    label: "Swift",
    icon: "logos:swift",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "kotlin",
    label: "Kotlin",
    icon: "logos:kotlin-icon",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "electron",
    label: "Electron",
    icon: "logos:electron",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "tauri",
    label: "Tauri",
    icon: "logos:tauri",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "blazor",
    label: "Blazor",
    icon: "logos:blazor",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "htmx",
    label: "HTMX",
    icon: "logos:htmx-icon",
    category: "frontend",
    defaultType: "frontend",
  },

  // ==================== BACKEND ====================
  {
    id: "nodejs",
    label: "Node.js",
    icon: "logos:nodejs-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "python",
    label: "Python",
    icon: "logos:python",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "go",
    label: "Go",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "rust",
    label: "Rust",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "java",
    label: "Java",
    icon: "logos:java",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "dotnet",
    label: ".NET",
    icon: "logos:dotnet",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "php",
    label: "PHP",
    icon: "logos:php",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "ruby",
    label: "Ruby",
    icon: "logos:ruby",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "bun",
    label: "Bun",
    icon: "logos:bun",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "deno",
    label: "Deno",
    icon: "logos:deno",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elixir",
    label: "Elixir",
    icon: "logos:elixir",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "express",
    label: "Express.js",
    icon: "logos:express",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fastify",
    label: "Fastify",
    icon: "logos:fastify-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "nestjs",
    label: "NestJS",
    icon: "logos:nestjs",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fastapi",
    label: "FastAPI",
    icon: "logos:fastapi-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "django",
    label: "Django",
    icon: "logos:django-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "flask",
    label: "Flask",
    icon: "logos:flask",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "spring",
    label: "Spring Boot",
    icon: "logos:spring-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "laravel",
    label: "Laravel",
    icon: "logos:laravel",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "rails",
    label: "Ruby on Rails",
    icon: "logos:rails",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "gin",
    label: "Gin",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fiber",
    label: "Fiber",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "hono",
    label: "Hono",
    icon: "logos:hono",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elysia",
    label: "Elysia",
    icon: "logos:elysia",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "adonisjs",
    label: "AdonisJS",
    icon: "logos:adonisjs-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "phoenix",
    label: "Phoenix",
    icon: "logos:phoenix",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "actix",
    label: "Actix",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "axum",
    label: "Axum",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },

  // ==================== DATABASE ====================
  {
    id: "postgres",
    label: "PostgreSQL",
    icon: "logos:postgresql",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mysql",
    label: "MySQL",
    icon: "logos:mysql",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mongodb",
    label: "MongoDB",
    icon: "logos:mongodb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "redis",
    label: "Redis",
    icon: "logos:redis",
    category: "database",
    defaultType: "cache",
  },
  {
    id: "sqlite",
    label: "SQLite",
    icon: "logos:sqlite",
    category: "database",
    defaultType: "database",
  },
  {
    id: "cassandra",
    label: "Cassandra",
    icon: "logos:cassandra",
    category: "database",
    defaultType: "database",
  },
  {
    id: "cockroachdb",
    label: "CockroachDB",
    icon: "logos:cockroachdb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "couchdb",
    label: "CouchDB",
    icon: "logos:couchdb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "dynamodb",
    label: "DynamoDB",
    icon: "logos:aws-dynamodb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "elasticsearch",
    label: "Elasticsearch",
    icon: "logos:elasticsearch",
    category: "database",
    defaultType: "database",
  },
  {
    id: "firebase",
    label: "Firebase",
    icon: "logos:firebase",
    category: "database",
    defaultType: "database",
  },
  {
    id: "influxdb",
    label: "InfluxDB",
    icon: "logos:influxdb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mariadb",
    label: "MariaDB",
    icon: "logos:mariadb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "memcached",
    label: "Memcached",
    icon: "logos:memcached",
    category: "database",
    defaultType: "cache",
  },
  {
    id: "neo4j",
    label: "Neo4j",
    icon: "logos:neo4j",
    category: "database",
    defaultType: "database",
  },
  {
    id: "oracle",
    label: "Oracle",
    icon: "logos:oracle",
    category: "database",
    defaultType: "database",
  },
  {
    id: "planetscale",
    label: "PlanetScale",
    icon: "logos:planetscale",
    category: "database",
    defaultType: "database",
  },
  {
    id: "scylladb",
    label: "ScyllaDB",
    icon: "logos:scylladb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    icon: "logos:snowflake",
    category: "database",
    defaultType: "database",
  },
  {
    id: "supabase",
    label: "Supabase",
    icon: "logos:supabase-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "timescaledb",
    label: "TimescaleDB",
    icon: "logos:timescaledb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "turso",
    label: "Turso",
    icon: "logos:turso",
    category: "database",
    defaultType: "database",
  },

  // ==================== CLOUD ====================
  {
    id: "aws",
    label: "AWS",
    icon: "logos:aws",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "gcp",
    label: "Google Cloud",
    icon: "logos:google-cloud",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "azure",
    label: "Azure",
    icon: "logos:azure-icon",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "vercel",
    label: "Vercel",
    icon: "logos:vercel-icon",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "netlify",
    label: "Netlify",
    icon: "logos:netlify",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "heroku",
    label: "Heroku",
    icon: "logos:heroku-icon",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "digitalocean",
    label: "DigitalOcean",
    icon: "logos:digital-ocean",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "linode",
    label: "Linode",
    icon: "logos:linode",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "ovh",
    label: "OVH",
    icon: "logos:ovh",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "hetzner",
    label: "Hetzner",
    icon: "logos:hetzner",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "fly",
    label: "Fly.io",
    icon: "logos:fly-io",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "railway",
    label: "Railway",
    icon: "logos:railway-icon",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "render",
    label: "Render",
    icon: "logos:render",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    icon: "logos:cloudflare",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "docker",
    label: "Docker",
    icon: "logos:docker-icon",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    icon: "logos:kubernetes",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "terraform",
    label: "Terraform",
    icon: "logos:terraform-icon",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "ansible",
    label: "Ansible",
    icon: "logos:ansible",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "github-actions",
    label: "GitHub Actions",
    icon: "logos:github-actions",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "gitlab-ci",
    label: "GitLab CI",
    icon: "logos:gitlab",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "jenkins",
    label: "Jenkins",
    icon: "logos:jenkins",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "circleci",
    label: "CircleCI",
    icon: "logos:circleci",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "travis",
    label: "Travis CI",
    icon: "logos:travis-ci",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "argocd",
    label: "ArgoCD",
    icon: "logos:argo-icon",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "spinnaker",
    label: "Spinnaker",
    icon: "logos:spinnaker",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "azure-devops",
    label: "Azure DevOps",
    icon: "logos:azure-devops",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "prometheus",
    label: "Prometheus",
    icon: "logos:prometheus",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "grafana",
    label: "Grafana",
    icon: "logos:grafana",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "datadog",
    label: "Datadog",
    icon: "logos:datadog",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "newrelic",
    label: "New Relic",
    icon: "logos:new-relic",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "sentry",
    label: "Sentry",
    icon: "logos:sentry-icon",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "dynatrace",
    label: "Dynatrace",
    icon: "logos:dynatrace",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "honeycomb",
    label: "Honeycomb",
    icon: "logos:honeycomb",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "splunk",
    label: "Splunk",
    icon: "logos:splunk",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "jaeger",
    label: "Jaeger",
    icon: "logos:jaeger",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "zipkin",
    label: "Zipkin",
    icon: "logos:zipkin",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "nginx",
    label: "Nginx",
    icon: "logos:nginx",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "apache",
    label: "Apache",
    icon: "logos:apache",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "kong",
    label: "Kong",
    icon: "logos:kong",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "traefik",
    label: "Traefik",
    icon: "logos:traefik",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "envoy",
    label: "Envoy",
    icon: "logos:envoy-icon",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "consul",
    label: "Consul",
    icon: "logos:consul",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "vault",
    label: "Vault",
    icon: "logos:vault",
    category: "security",
    defaultType: "security",
  },
  {
    id: "istio",
    label: "Istio",
    icon: "logos:istio",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "linkerd",
    label: "Linkerd",
    icon: "logos:linkerd",
    category: "devops",
    defaultType: "service",
  },

  // ==================== AI / ML ====================
  // Cloud AI APIs
  {
    id: "openai",
    label: "OpenAI",
    icon: "logos:openai-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    icon: "logos:anthropic-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "google-gemini",
    label: "Google Gemini",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "azure-openai",
    label: "Azure OpenAI",
    icon: "logos:azure-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "aws-bedrock",
    label: "AWS Bedrock",
    icon: "logos:aws",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "vertex-ai",
    label: "Vertex AI",
    icon: "logos:google-cloud",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "cohere",
    label: "Cohere",
    icon: "logos:cohere",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "mistral",
    label: "Mistral AI",
    icon: "logos:mistral-ai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "ai21",
    label: "AI21 Labs",
    icon: "logos:ai21",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "replicate",
    label: "Replicate",
    icon: "logos:replicate",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    icon: "logos:huggingface-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "groq",
    label: "Groq",
    icon: "logos:groq",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    icon: "logos:perplexity",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "together",
    label: "Together AI",
    icon: "logos:together-ai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    icon: "logos:fireworks",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "baseten",
    label: "Baseten",
    icon: "logos:baseten",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "anyscale",
    label: "Anyscale",
    icon: "logos:anyscale",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "octoml",
    label: "OctoML",
    icon: "logos:octoml",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    icon: "logos:deepinfra",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "predibase",
    label: "Predibase",
    icon: "logos:predibase",
    category: "ai",
    defaultType: "ai",
  },

  // Local AI Tools
  {
    id: "ollama",
    label: "Ollama",
    icon: "logos:ollama",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "lm-studio",
    label: "LM Studio",
    icon: "logos:lmstudio",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "vllm",
    label: "vLLM",
    icon: "logos:vllm",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "llamacpp",
    label: "llama.cpp",
    icon: "logos:llamacpp",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "localai",
    label: "LocalAI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "jan",
    label: "Jan",
    icon: "logos:jan",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "text-generation-webui",
    label: "Text Generation WebUI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "koboldcpp",
    label: "KoboldCPP",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "tabby",
    label: "Tabby",
    icon: "logos:tabby",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "continue",
    label: "Continue",
    icon: "logos:continue",
    category: "ai",
    defaultType: "ai-model",
  },

  // AI Frameworks & Tools
  {
    id: "langchain",
    label: "LangChain",
    icon: "logos:langchain",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "llamaindex",
    label: "LlamaIndex",
    icon: "logos:llamaindex",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "haystack",
    label: "Haystack",
    icon: "logos:haystack",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "semantic-kernel",
    label: "Semantic Kernel",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "autogen",
    label: "AutoGen",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "crewai",
    label: "CrewAI",
    icon: "logos:crewai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "langgraph",
    label: "LangGraph",
    icon: "logos:langchain",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "promptflow",
    label: "Prompt Flow",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    icon: "logos:openrouter",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "litellm",
    label: "LiteLLM",
    icon: "logos:litellm",
    category: "ai",
    defaultType: "ai",
  },

  // Open Source Models (will use bot icon as fallback)
  {
    id: "llama",
    label: "Llama",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "mistral-7b",
    label: "Mistral 7B",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "mixtral",
    label: "Mixtral",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    icon: "logos:deepseek",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "qwen",
    label: "Qwen",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gemma",
    label: "Gemma",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "phi",
    label: "Phi",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "command-r",
    label: "Command R",
    icon: "logos:cohere",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "starcoder",
    label: "StarCoder",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "codellama",
    label: "CodeLlama",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "wizardcoder",
    label: "WizardCoder",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "dolphin",
    label: "Dolphin",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "neural-chat",
    label: "Neural Chat",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "openchat",
    label: "OpenChat",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "yi",
    label: "Yi",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "falcon",
    label: "Falcon",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "mpt",
    label: "MPT",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gpt4all",
    label: "GPT4All",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },

  // ==================== VECTOR DATABASES ====================
  {
    id: "pinecone",
    label: "Pinecone",
    icon: "logos:pinecone",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "weaviate",
    label: "Weaviate",
    icon: "logos:weaviate",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "chroma",
    label: "Chroma",
    icon: "logos:chroma",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "qdrant",
    label: "Qdrant",
    icon: "logos:qdrant",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "milvus",
    label: "Milvus",
    icon: "logos:milvus",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "pgvector",
    label: "pgvector",
    icon: "logos:postgresql",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "faiss",
    label: "FAISS",
    icon: "logos:meta",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "redis-vector",
    label: "Redis Vector",
    icon: "logos:redis",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "lancedb",
    label: "LanceDB",
    icon: "logos:lancedb",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "deeplake",
    label: "Deep Lake",
    icon: "logos:activeloop",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "vespa",
    label: "Vespa",
    icon: "logos:vespa",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "typesense",
    label: "Typesense",
    icon: "logos:typesense",
    category: "vector-db",
    defaultType: "vector-db",
  },

  // ==================== AUTH & IDENTITY ====================
  {
    id: "clerk",
    label: "Clerk",
    icon: "logos:clerk",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "auth0",
    label: "Auth0",
    icon: "logos:auth0",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "firebase-auth",
    label: "Firebase Auth",
    icon: "logos:firebase",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "supabase-auth",
    label: "Supabase Auth",
    icon: "logos:supabase-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "nextauth",
    label: "NextAuth.js",
    icon: "logos:nextjs-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "authjs",
    label: "Auth.js",
    icon: "logos:authjs",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "aws-cognito",
    label: "AWS Cognito",
    icon: "logos:aws",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "azure-ad",
    label: "Azure AD",
    icon: "logos:azure-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "keycloak",
    label: "Keycloak",
    icon: "logos:keycloak",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "okta",
    label: "Okta",
    icon: "logos:okta",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "onelogin",
    label: "OneLogin",
    icon: "logos:onelogin",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "workos",
    label: "WorkOS",
    icon: "logos:workos",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "fusionauth",
    label: "FusionAuth",
    icon: "logos:fusionauth",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "authelia",
    label: "Authelia",
    icon: "logos:authelia",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "authentik",
    label: "Authentik",
    icon: "logos:authentik",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "logto",
    label: "Logto",
    icon: "logos:logto",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "supertokens",
    label: "SuperTokens",
    icon: "logos:supertokens",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "zitadel",
    label: "ZITADEL",
    icon: "logos:zitadel",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "casdoor",
    label: "Casdoor",
    icon: "logos:casdoor",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "ory",
    label: "Ory",
    icon: "logos:ory",
    category: "auth",
    defaultType: "auth",
  },

  // ==================== PAYMENT GATEWAYS ====================
  {
    id: "stripe",
    label: "Stripe",
    icon: "logos:stripe",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "paypal",
    label: "PayPal",
    icon: "logos:paypal",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "adyen",
    label: "Adyen",
    icon: "logos:adyen",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "square",
    label: "Square",
    icon: "logos:square",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "braintree",
    label: "Braintree",
    icon: "logos:braintree",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "lemon-squeezy",
    label: "Lemon Squeezy",
    icon: "logos:lemonsqueezy",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "paddle",
    label: "Paddle",
    icon: "logos:paddle",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "razorpay",
    label: "Razorpay",
    icon: "logos:razorpay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "mollie",
    label: "Mollie",
    icon: "logos:mollie",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "klarna",
    label: "Klarna",
    icon: "logos:klarna",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "afterpay",
    label: "Afterpay",
    icon: "logos:afterpay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "affirm",
    label: "Affirm",
    icon: "logos:affirm",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "shopify-payments",
    label: "Shopify Payments",
    icon: "logos:shopify",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "amazon-pay",
    label: "Amazon Pay",
    icon: "logos:amazon-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "apple-pay",
    label: "Apple Pay",
    icon: "logos:apple-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "google-pay",
    label: "Google Pay",
    icon: "logos:google-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "alipay",
    label: "Alipay",
    icon: "logos:alipay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "wechat-pay",
    label: "WeChat Pay",
    icon: "logos:wechat",
    category: "payment",
    defaultType: "payment",
  },

  // ==================== AUTOMATION & INTEGRATION ====================
  {
    id: "n8n",
    label: "n8n",
    icon: "logos:n8n",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "zapier",
    label: "Zapier",
    icon: "logos:zapier",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "make",
    label: "Make",
    icon: "logos:make",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "workato",
    label: "Workato",
    icon: "logos:workato",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "tray",
    label: "Tray.io",
    icon: "logos:tray",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "mulesoft",
    label: "MuleSoft",
    icon: "logos:mulesoft",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "boomi",
    label: "Boomi",
    icon: "logos:boomi",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "ifttt",
    label: "IFTTT",
    icon: "logos:ifttt",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "huginn",
    label: "Huginn",
    icon: "lucide:bot",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "node-red",
    label: "Node-RED",
    icon: "logos:node-red",
    category: "automation",
    defaultType: "automation",
  },

  // ==================== MESSAGING & COMMUNICATION ====================
  {
    id: "twilio",
    label: "Twilio",
    icon: "logos:twilio",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "sendgrid",
    label: "SendGrid",
    icon: "logos:sendgrid",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "mailgun",
    label: "Mailgun",
    icon: "logos:mailgun",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "postmark",
    label: "Postmark",
    icon: "logos:postmark",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "mailchimp",
    label: "Mailchimp",
    icon: "logos:mailchimp",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "pusher",
    label: "Pusher",
    icon: "logos:pusher",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "ably",
    label: "Ably",
    icon: "logos:ably",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "pubnub",
    label: "PubNub",
    icon: "logos:pubnub",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "socketio",
    label: "Socket.io",
    icon: "logos:socket.io",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "onesignal",
    label: "OneSignal",
    icon: "logos:onesignal",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "firebase-cloud-messaging",
    label: "FCM",
    icon: "logos:firebase",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "aws-sns",
    label: "AWS SNS",
    icon: "logos:aws",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "aws-sqs",
    label: "AWS SQS",
    icon: "logos:aws",
    category: "messaging",
    defaultType: "queue",
  },
  {
    id: "rabbitmq",
    label: "RabbitMQ",
    icon: "logos:rabbitmq",
    category: "messaging",
    defaultType: "queue",
  },
  {
    id: "kafka",
    label: "Kafka",
    icon: "logos:kafka-icon",
    category: "messaging",
    defaultType: "queue",
  },
  {
    id: "nats",
    label: "NATS",
    icon: "logos:nats",
    category: "messaging",
    defaultType: "queue",
  },
  {
    id: "pulsar",
    label: "Pulsar",
    icon: "logos:apache-pulsar",
    category: "messaging",
    defaultType: "queue",
  },
  {
    id: "mqtt",
    label: "MQTT",
    icon: "logos:mqtt",
    category: "messaging",
    defaultType: "messaging",
  },

  // ==================== SEARCH & ANALYTICS ====================
  {
    id: "algolia",
    label: "Algolia",
    icon: "logos:algolia",
    category: "search",
    defaultType: "search",
  },
  {
    id: "meilisearch",
    label: "Meilisearch",
    icon: "logos:meilisearch",
    category: "search",
    defaultType: "search",
  },
  {
    id: "typesense",
    label: "Typesense",
    icon: "logos:typesense",
    category: "search",
    defaultType: "search",
  },
  {
    id: "mixpanel",
    label: "Mixpanel",
    icon: "logos:mixpanel",
    category: "search",
    defaultType: "search",
  },
  {
    id: "amplitude",
    label: "Amplitude",
    icon: "logos:amplitude",
    category: "search",
    defaultType: "search",
  },
  {
    id: "segment",
    label: "Segment",
    icon: "logos:segment",
    category: "search",
    defaultType: "search",
  },
  {
    id: "posthog",
    label: "PostHog",
    icon: "logos:posthog",
    category: "search",
    defaultType: "search",
  },
  {
    id: "plausible",
    label: "Plausible",
    icon: "logos:plausible",
    category: "search",
    defaultType: "search",
  },
  {
    id: "umami",
    label: "Umami",
    icon: "logos:umami",
    category: "search",
    defaultType: "search",
  },
  {
    id: "fathom",
    label: "Fathom",
    icon: "logos:fathom",
    category: "search",
    defaultType: "search",
  },
  {
    id: "google-analytics",
    label: "Google Analytics",
    icon: "logos:google-analytics",
    category: "search",
    defaultType: "search",
  },
  {
    id: "hotjar",
    label: "Hotjar",
    icon: "logos:hotjar",
    category: "search",
    defaultType: "search",
  },
  {
    id: "fullstory",
    label: "FullStory",
    icon: "logos:fullstory",
    category: "search",
    defaultType: "search",
  },
  {
    id: "logrocket",
    label: "LogRocket",
    icon: "logos:logrocket",
    category: "search",
    defaultType: "search",
  },
  {
    id: "heap",
    label: "Heap",
    icon: "logos:heap",
    category: "search",
    defaultType: "search",
  },

  // ==================== SECURITY ====================
  {
    id: "cloudflare-waf",
    label: "Cloudflare WAF",
    icon: "logos:cloudflare",
    category: "security",
    defaultType: "security",
  },
  {
    id: "aws-waf",
    label: "AWS WAF",
    icon: "logos:aws",
    category: "security",
    defaultType: "security",
  },
  {
    id: "snyk",
    label: "Snyk",
    icon: "logos:snyk",
    category: "security",
    defaultType: "security",
  },
  {
    id: "sonarqube",
    label: "SonarQube",
    icon: "logos:sonarqube",
    category: "security",
    defaultType: "security",
  },
  {
    id: "trivy",
    label: "Trivy",
    icon: "logos:trivy",
    category: "security",
    defaultType: "security",
  },
  {
    id: "checkmarx",
    label: "Checkmarx",
    icon: "logos:checkmarx",
    category: "security",
    defaultType: "security",
  },
  {
    id: "veracode",
    label: "Veracode",
    icon: "logos:veracode",
    category: "security",
    defaultType: "security",
  },
  {
    id: "authy",
    label: "Authy",
    icon: "logos:authy",
    category: "security",
    defaultType: "security",
  },
  {
    id: "1password",
    label: "1Password",
    icon: "logos:1password",
    category: "security",
    defaultType: "security",
  },
  {
    id: "bitwarden",
    label: "Bitwarden",
    icon: "logos:bitwarden",
    category: "security",
    defaultType: "security",
  },
  {
    id: "crowdstrike",
    label: "CrowdStrike",
    icon: "logos:crowdstrike",
    category: "security",
    defaultType: "security",
  },
  {
    id: "okta-security",
    label: "Okta Security",
    icon: "logos:okta",
    category: "security",
    defaultType: "security",
  },
  {
    id: "burp-suite",
    label: "Burp Suite",
    icon: "logos:burp-suite",
    category: "security",
    defaultType: "security",
  },
  {
    id: "owasp-zap",
    label: "OWASP ZAP",
    icon: "logos:owasp",
    category: "security",
    defaultType: "security",
  },

  // ==================== TESTING ====================
  {
    id: "cypress",
    label: "Cypress",
    icon: "logos:cypress-icon",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "playwright",
    label: "Playwright",
    icon: "logos:playwright",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "selenium",
    label: "Selenium",
    icon: "logos:selenium",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "jest",
    label: "Jest",
    icon: "logos:jest",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "vitest",
    label: "Vitest",
    icon: "logos:vitest",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "mocha",
    label: "Mocha",
    icon: "logos:mocha",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "k6",
    label: "k6",
    icon: "logos:k6",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "artillery",
    label: "Artillery",
    icon: "logos:artillery",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "storybook",
    label: "Storybook",
    icon: "logos:storybook-icon",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "chromatic",
    label: "Chromatic",
    icon: "logos:chromatic",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "percy",
    label: "Percy",
    icon: "logos:percy",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "detox",
    label: "Detox",
    icon: "logos:detox",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "appium",
    label: "Appium",
    icon: "logos:appium",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "gatling",
    label: "Gatling",
    icon: "logos:gatling",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "locust",
    label: "Locust",
    icon: "logos:locust",
    category: "testing",
    defaultType: "testing",
  },

  // ==================== STORAGE ====================
  {
    id: "s3",
    label: "Amazon S3",
    icon: "logos:aws-s3",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "gcs",
    label: "Google Cloud Storage",
    icon: "logos:google-cloud",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "azure-blob",
    label: "Azure Blob Storage",
    icon: "logos:azure-icon",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "cloudflare-r2",
    label: "Cloudflare R2",
    icon: "logos:cloudflare",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "minio",
    label: "MinIO",
    icon: "logos:minio",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "backblaze",
    label: "Backblaze B2",
    icon: "logos:backblaze",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "wasabi",
    label: "Wasabi",
    icon: "logos:wasabi",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "dropbox",
    label: "Dropbox",
    icon: "logos:dropbox",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "box",
    label: "Box",
    icon: "logos:box",
    category: "storage",
    defaultType: "storage",
  },

  // ==================== COMPUTE ====================
  {
    id: "lambda",
    label: "AWS Lambda",
    icon: "logos:aws-lambda",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "cloud-run",
    label: "Cloud Run",
    icon: "logos:google-cloud",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "azure-functions",
    label: "Azure Functions",
    icon: "logos:azure-icon",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "cloudflare-workers",
    label: "Cloudflare Workers",
    icon: "logos:cloudflare",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "ecs",
    label: "AWS ECS",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "eks",
    label: "AWS EKS",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "fargate",
    label: "AWS Fargate",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "ec2",
    label: "Amazon EC2",
    icon: "logos:aws-ec2",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "gke",
    label: "Google Kubernetes Engine",
    icon: "logos:google-cloud",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "aks",
    label: "Azure Kubernetes Service",
    icon: "logos:azure-icon",
    category: "compute",
    defaultType: "service",
  },

  // ==================== AWS SERVICES ====================
  {
    id: "aws-api-gateway",
    label: "AWS API Gateway",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-app-mesh",
    label: "AWS App Mesh",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-app-sync",
    label: "AWS AppSync",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-batch",
    label: "AWS Batch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "compute",
  },
  {
    id: "aws-cloudformation",
    label: "AWS CloudFormation",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-cloudfront",
    label: "AWS CloudFront",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-cloudtrail",
    label: "AWS CloudTrail",
    icon: "logos:aws",
    category: "aws",
    defaultType: "monitoring",
  },
  {
    id: "aws-cloudwatch",
    label: "AWS CloudWatch",
    icon: "logos:aws-cloudwatch",
    category: "aws",
    defaultType: "monitoring",
  },
  {
    id: "aws-codebuild",
    label: "AWS CodeBuild",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codecommit",
    label: "AWS CodeCommit",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codedeploy",
    label: "AWS CodeDeploy",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codepipeline",
    label: "AWS CodePipeline",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-config",
    label: "AWS Config",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-documentdb",
    label: "AWS DocumentDB",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-elasticache",
    label: "AWS ElastiCache",
    icon: "logos:aws-elasticache",
    category: "aws",
    defaultType: "cache",
  },
  {
    id: "aws-elasticsearch",
    label: "AWS Elasticsearch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-eventbridge",
    label: "AWS EventBridge",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-glue",
    label: "AWS Glue",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-iam",
    label: "AWS IAM",
    icon: "logos:aws-iam",
    category: "aws",
    defaultType: "auth",
  },
  {
    id: "aws-kinesis",
    label: "AWS Kinesis",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-kms",
    label: "AWS KMS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-lake-formation",
    label: "AWS Lake Formation",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-lambda",
    label: "AWS Lambda",
    icon: "logos:aws-lambda",
    category: "aws",
    defaultType: "function",
  },
  {
    id: "aws-mq",
    label: "AWS MQ",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-msk",
    label: "AWS MSK",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-neptune",
    label: "AWS Neptune",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-opensearch",
    label: "AWS OpenSearch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-pinpoint",
    label: "AWS Pinpoint",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-quicksight",
    label: "AWS QuickSight",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-rds",
    label: "AWS RDS",
    icon: "logos:aws-rds",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-redshift",
    label: "AWS Redshift",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-route53",
    label: "AWS Route 53",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-sagemaker",
    label: "AWS SageMaker",
    icon: "logos:aws",
    category: "aws",
    defaultType: "ai",
  },
  {
    id: "aws-secrets-manager",
    label: "AWS Secrets Manager",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-shield",
    label: "AWS Shield",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-snowball",
    label: "AWS Snowball",
    icon: "logos:aws",
    category: "aws",
    defaultType: "storage",
  },
  {
    id: "aws-sns",
    label: "AWS SNS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-sqs",
    label: "AWS SQS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-step-functions",
    label: "AWS Step Functions",
    icon: "logos:aws",
    category: "aws",
    defaultType: "automation",
  },
  {
    id: "aws-textract",
    label: "AWS Textract",
    icon: "logos:aws",
    category: "aws",
    defaultType: "ai",
  },
  {
    id: "aws-transit-gateway",
    label: "AWS Transit Gateway",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-vpc",
    label: "AWS VPC",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-xray",
    label: "AWS X-Ray",
    icon: "logos:aws",
    category: "aws",
    defaultType: "monitoring",
  },

  // ==================== GCP SERVICES ====================
  {
    id: "gcp-app-engine",
    label: "App Engine",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "compute",
  },
  {
    id: "gcp-bigquery",
    label: "BigQuery",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-bigtable",
    label: "Cloud Bigtable",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-build",
    label: "Cloud Build",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "cicd",
  },
  {
    id: "gcp-cdn",
    label: "Cloud CDN",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-composer",
    label: "Cloud Composer",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dataflow",
    label: "Cloud Dataflow",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-datafusion",
    label: "Cloud Data Fusion",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dataproc",
    label: "Cloud Dataproc",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dns",
    label: "Cloud DNS",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-endpoints",
    label: "Cloud Endpoints",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-eventarc",
    label: "Eventarc",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-filestore",
    label: "Cloud Filestore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "storage",
  },
  {
    id: "gcp-firestore",
    label: "Cloud Firestore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-functions",
    label: "Cloud Functions",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "function",
  },
  {
    id: "gcp-iam",
    label: "Cloud IAM",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "auth",
  },
  {
    id: "gcp-iot",
    label: "Cloud IoT",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-kms",
    label: "Cloud KMS",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "security",
  },
  {
    id: "gcp-load-balancing",
    label: "Cloud Load Balancing",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-logging",
    label: "Cloud Logging",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-memorystore",
    label: "Cloud Memorystore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "cache",
  },
  {
    id: "gcp-monitoring",
    label: "Cloud Monitoring",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-nat",
    label: "Cloud NAT",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-pubsub",
    label: "Cloud Pub/Sub",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-run",
    label: "Cloud Run",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "compute",
  },
  {
    id: "gcp-scheduler",
    label: "Cloud Scheduler",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "automation",
  },
  {
    id: "gcp-secret-manager",
    label: "Secret Manager",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "security",
  },
  {
    id: "gcp-spanner",
    label: "Cloud Spanner",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-speech",
    label: "Cloud Speech-to-Text",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-sql",
    label: "Cloud SQL",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-storage",
    label: "Cloud Storage",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "storage",
  },
  {
    id: "gcp-tasks",
    label: "Cloud Tasks",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-tpu",
    label: "Cloud TPU",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-trace",
    label: "Cloud Trace",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-translate",
    label: "Cloud Translation",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-video",
    label: "Cloud Video",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-vision",
    label: "Cloud Vision",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-vpc",
    label: "VPC",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-workflows",
    label: "Cloud Workflows",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "automation",
  },
  // ==================== 2026 ECOSYSTEM ADDITIONS ====================
  // Frontend Meta-Frameworks
  {
    id: "solid-start",
    label: "SolidStart",
    icon: "logos:solidjs-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-start",
    label: "TanStack Start",
    icon: "simple-icons:react", // Fallback or find specific
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "react-router",
    label: "React Router v7",
    icon: "logos:react-router",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "million",
    label: "Million.js",
    icon: "logos:million",
    category: "frontend",
    defaultType: "frontend",
  },

  // Backend Runtimes & Frameworks
  {
    id: "workerd",
    label: "workerd (Cloudflare)",
    icon: "logos:cloudflare-workers-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "nitro",
    label: "Nitro",
    icon: "logos:nitro-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "hattip",
    label: "Hattip",
    icon: "carbon:http", // Generic HTTP icon
    category: "backend",
    defaultType: "backend",
  },

  // Database & Data
  {
    id: "neon",
    label: "Neon",
    icon: "logos:neon-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "convex",
    label: "Convex",
    icon: "logos:convex-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "upstash",
    label: "Upstash",
    icon: "logos:upstash-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "val-town",
    label: "Val Town",
    icon: "carbon:function",
    category: "backend",
    defaultType: "function",
  },

  // AI & Agents
  {
    id: "langgraph",
    label: "LangGraph",
    icon: "simple-icons:langchain",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "crewai",
    label: "CrewAI",
    icon: "fluent-emoji-high-contrast:robot", // Fallback
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "pydantic-ai",
    label: "PydanticAI",
    icon: "simple-icons:pydantic",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "openai-o1",
    label: "OpenAI o1",
    icon: "logos:openai-icon",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gemini-pro",
    label: "Gemini 1.5 Pro",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "deepseek-v3",
    label: "DeepSeek v3",
    icon: "arcticons:deepseek", // Check generic support
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "unstructured",
    label: "Unstructured.io",
    icon: "lucide:file-text",
    category: "ai",
    defaultType: "service",
  },

  // Real-time
  {
    id: "partykit",
    label: "PartyKit",
    icon: "lucide:party-popper",
    category: "backend",
    defaultType: "server",
  },
  {
    id: "liveblocks",
    label: "Liveblocks",
    icon: "logos:liveblocks-icon",
    category: "tooling",
    defaultType: "service",
  },

  // Platform & DevOps
  {
    id: "backstage",
    label: "Backstage",
    icon: "logos:backstage-icon",
    category: "devops",
    defaultType: "idp",
  },
  {
    id: "port",
    label: "GetPort",
    icon: "simple-icons:port",
    category: "devops",
    defaultType: "idp",
  },
  {
    id: "opentofu",
    label: "OpenTofu",
    icon: "logos:opentofu",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "dagger",
    label: "Dagger",
    icon: "logos:dagger-icon",
    category: "devops",
    defaultType: "cicd",
  },
];

// Helper function to get tech by ID
export function getTechById(id: string): TechItem | undefined {
  return TECH_ECOSYSTEM.find((tech) => tech.id === id);
}

// Helper function to get techs by category
export function getTechsByCategory(category: TechCategory): TechItem[] {
  return TECH_ECOSYSTEM.filter((tech) => tech.category === category);
}

// Helper function to get techs by default type
export function getTechsByType(type: string): TechItem[] {
  return TECH_ECOSYSTEM.filter((tech) => tech.defaultType === type);
}
