/**
 * Tech Name Normalizer
 * Maps AI-generated tech names to TECH_ECOSYSTEM IDs for consistent icon lookup
 */

import { TECH_ECOSYSTEM, type TechItem } from "./tech-ecosystem";

// Common variations and aliases
const TECH_ALIASES: Record<string, string> = {
  // Frontend
  "next.js": "nextjs",
  next: "nextjs",
  "next.js frontend": "nextjs",
  nuxtjs: "nuxt",
  "nuxt.js": "nuxt",
  "react.js": "react",
  "vue.js": "vue",
  vuejs: "vue",
  "svelte.js": "svelte",
  "sveltekit.js": "sveltekit",
  "vite.js": "vite",
  "react native": "react-native",
  rn: "react-native",
  electronjs: "electron",
  tauriapp: "tauri",
  "blazor wasm": "blazor",

  // Backend
  "node.js": "nodejs",
  node: "nodejs",
  "express.js": "express",
  "nest.js": "nestjs",
  nest: "nestjs",
  "fast api": "fastapi",
  "spring boot": "spring",
  springboot: "spring",
  laravelphp: "laravel",
  railsruby: "rails",
  phoenixframework: "phoenix",
  elixirphoenix: "phoenix",
  golang: "go",
  gorm: "go",
  dotnetcore: "dotnet",
  "asp.net": "dotnet",
  aspnet: "dotnet",
  bunjs: "bun",
  denoland: "deno",

  // Database
  postgresql: "postgres",
  postgres: "postgres",
  psql: "postgres",
  mongo: "mongodb",
  "mongo db": "mongodb",
  "mongodb atlas": "mongodb",
  "supabase postgresql": "supabase",
  "supabase postgres": "supabase",
  cockroach: "cockroachdb",
  "cockroach labs": "cockroachdb",
  timescale: "timescaledb",
  planetscaledb: "planetscale",
  scylla: "scylladb",
  cassandradb: "cassandra",
  "mariadb mysql": "mariadb",
  "neo4j graph": "neo4j",
  "redis cache": "redis",
  redisdb: "redis",

  // Cloud
  "amazon web services": "aws",
  amazonaws: "aws",
  "google cloud platform": "gcp",
  googlecloud: "gcp",
  "microsoft azure": "azure",
  azurecloud: "azure",
  do: "digitalocean",
  "digitalocean cloud": "digitalocean",
  hetznercloud: "hetzner",
  ovhcloud: "ovh",
  linodecloud: "linode",
  "akamai linode": "linode",
  "cloudflare workers": "cloudflare-workers",
  "cloudflare r2": "cloudflare-r2",
  r2storage: "cloudflare-r2",
  workersdev: "cloudflare-workers",
  vercelapp: "vercel",
  railwayapp: "railway",
  rendercom: "render",
  flyio: "fly",

  // AI - Cloud APIs
  "open ai": "openai",
  openaiapi: "openai",
  chatgpt: "openai",
  gpt4: "openai",
  gpt3: "openai",
  gpt: "openai",
  claudeai: "anthropic",
  "claude ai": "anthropic",
  claude3: "anthropic",
  claude35: "anthropic",
  claudesonnet: "anthropic",
  claudeopus: "anthropic",
  "google gemini": "google-gemini",
  geminipro: "google-gemini",
  geminiapi: "google-gemini",
  bard: "google-gemini",
  palm: "google-gemini",
  vertexai: "vertex-ai",
  "azure openai": "azure-openai",
  azureopenai: "azure-openai",
  "aws bedrock": "aws-bedrock",
  amazonbedrock: "aws-bedrock",
  "amazon bedrock": "aws-bedrock",
  cohereai: "cohere",
  "cohere ai": "cohere",
  mistralai: "mistral",
  "mistral ai": "mistral",
  mistral7b: "mistral",
  mixtral8x7b: "mixtral",
  "ai21 labs": "ai21",
  jurassic: "ai21",
  replicateai: "replicate",
  "hugging face": "huggingface",
  hf: "huggingface",
  "huggingface transformers": "huggingface",
  groqai: "groq",
  "groq ai": "groq",
  perplexityai: "perplexity",
  "perplexity ai": "perplexity",
  togetherai: "together",
  "together ai": "together",
  fireworksai: "fireworks",
  "fireworks ai": "fireworks",
  basetenml: "baseten",
  anyscaleai: "anyscale",
  octomlai: "octoml",
  deepinfraai: "deepinfra",
  predibaseai: "predibase",

  // AI - Local/Models
  "meta llama": "llama",
  llama2: "llama",
  llama3: "llama",
  "llama 2": "llama",
  "llama 3": "llama",
  llama31: "llama",
  llama32: "llama",
  llama70b: "llama",
  "llama 70b": "llama",
  "mistral 7b": "mistral-7b",
  mixtral: "mixtral",
  "mixtral 8x7b": "mixtral",
  deepseekai: "deepseek",
  "deep seek": "deepseek",
  deepseekcoder: "deepseek",
  deepseekchat: "deepseek",
  qwen2: "qwen",
  qwen7b: "qwen",
  qwen14b: "qwen",
  qwen72b: "qwen",
  "google gemma": "gemma",
  gemma2b: "gemma",
  gemma7b: "gemma",
  "phi 3": "phi",
  phi3: "phi",
  phimini: "phi",
  commandr: "command-r",
  commandrplus: "command-r",
  starcoder2: "starcoder",
  codellama70b: "codellama",
  codellamapython: "codellama",
  wizardlm: "wizardcoder",
  "dolphin mistral": "dolphin",
  neuralchat7b: "neural-chat",
  openchat35: "openchat",
  yi34b: "yi",
  falcon40b: "falcon",
  falcon180b: "falcon",
  mpt7b: "mpt",
  mpt30b: "mpt",
  gpt4allj: "gpt4all",

  // AI - Local Tools
  ollamaai: "ollama",
  "ollama ai": "ollama",
  lmstudioai: "lm-studio",
  lmstudio: "lm-studio",
  "lm studio": "lm-studio",
  vllminference: "vllm",
  llamacpplib: "llamacpp",
  "llama cpp": "llamacpp",
  localaillm: "localai",
  janai: "jan",
  "jan ai": "jan",
  textgenwebui: "text-generation-webui",
  textgenerationwebui: "text-generation-webui",
  koboldcppai: "koboldcpp",
  tabbyml: "tabby",
  continueai: "continue",
  "continue.dev": "continue",

  // AI - Frameworks
  langchainjs: "langchain",
  langchainpy: "langchain",
  langchainpython: "langchain",
  llamaindexgpt: "llamaindex",
  gptindex: "llamaindex",
  haystacknlp: "haystack",
  semantickernelai: "semantic-kernel",
  "semantic kernel": "semantic-kernel",
  autogenmicrosoft: "autogen",
  crewaiagents: "crewai",
  langgraphai: "langgraph",
  promptflowai: "promptflow",
  openrouterai: "openrouter",
  "open router": "openrouter",
  litellmproxy: "litellm",

  // Vector DBs
  pineconedb: "pinecone",
  pineconeio: "pinecone",
  weaviatedb: "weaviate",
  semitechnologies: "weaviate",
  chromadb: "chroma",
  trychroma: "chroma",
  qdrantdb: "qdrant",
  milvusdb: "milvus",
  zilliz: "milvus",
  pgvectordb: "pgvector",
  faissdb: "faiss",
  metaai: "faiss",
  redisvector: "redis-vector",
  lancedblabs: "lancedb",
  deeplakeai: "deeplake",
  activeloop: "deeplake",
  vespadb: "vespa",
  typesensesearch: "typesense",

  // Auth
  clerkauth: "clerk",
  clerkdev: "clerk",
  auth0okta: "auth0",
  firebaseauthentication: "firebase-auth",
  "firebase auth": "firebase-auth",
  supabaseauthjs: "supabase-auth",
  nextauthjs: "nextauth",
  "next auth": "nextauth",
  nextauthv5: "nextauth",
  authjsdev: "authjs",
  cognitoaws: "aws-cognito",
  amazoncognito: "aws-cognito",
  azureadb2c: "azure-ad",
  "azure ad": "azure-ad",
  keycloakauth: "keycloak",
  okatauth: "okta",
  oktadeveloper: "okta",
  oneloginauth: "onelogin",
  workosauthkit: "workos",
  fusionauthio: "fusionauth",
  autheliaserver: "authelia",
  authentiksecurity: "authentik",
  logtoauth: "logto",
  supertokensio: "supertokens",
  zitadelcloud: "zitadel",
  casdoorauth: "casdoor",
  oryauth: "ory",
  kratosory: "ory",

  // Payment
  stripepayments: "stripe",
  stripeapi: "stripe",
  paypalcheckout: "paypal",
  paypalsdk: "paypal",
  adyenpayments: "adyen",
  squarepayments: "square",
  braintreepayments: "braintree",
  braintreesdk: "braintree",
  lemonsqueezyapp: "lemon-squeezy",
  "lemon squeezy": "lemon-squeezy",
  paddlebilling: "paddle",
  razorpayindia: "razorpay",
  mollieeu: "mollie",
  klarnapayments: "klarna",
  afterpayclearpay: "afterpay",
  affirmpay: "affirm",
  shopifypay: "shopify-payments",
  amazonpay: "amazon-pay",
  applepay: "apple-pay",
  googlepay: "google-pay",
  alipaychina: "alipay",
  wechatpaychina: "wechat-pay",

  // Automation
  n8nio: "n8n",
  n8nworkflow: "n8n",
  zapierautomation: "zapier",
  integromat: "make",
  makeworkflow: "make",
  workatoipaas: "workato",
  trayworkflow: "tray",
  mulesoftanypoint: "mulesoft",
  boomidell: "boomi",
  iftttapplet: "ifttt",
  ifthisthenthat: "ifttt",
  huginnagents: "huginn",
  noderedflow: "node-red",
  "node red": "node-red",

  // Messaging
  twiliosms: "twilio",
  twilioapi: "twilio",
  sendgridmail: "sendgrid",
  twiliosendgrid: "sendgrid",
  mailgundev: "mailgun",
  postmarkapp: "postmark",
  mailchimpsend: "mailchimp",
  pushercom: "pusher",
  pusherjs: "pusher",
  ablyio: "ably",
  pubnubrealtime: "pubnub",
  socketiojs: "socketio",
  "socket.io": "socketio",
  onesignalpush: "onesignal",
  fcmfirebase: "firebase-cloud-messaging",
  awsamazonmq: "aws-mq",
  amazonmq: "aws-mq",
  mskkafka: "aws-msk",
  amazonmsk: "aws-msk",
  rabbitmqserver: "rabbitmq",
  kafkastreams: "kafka",
  apachekafka: "kafka",
  natsio: "nats",
  synadiacloud: "nats",
  pulsarapache: "pulsar",
  apachepulsar: "pulsar",
  mqttbroker: "mqtt",
  mosquitto: "mqtt",

  // Search/Analytics
  algoliasearch: "algolia",
  meilisearchrust: "meilisearch",
  mixpanelanalytics: "mixpanel",
  amplitudeanalytics: "amplitude",
  segmentio: "segment",
  twiliosegment: "segment",
  posthogcom: "posthog",
  plausibleio: "plausible",
  umamiis: "umami",
  fathomanalytics: "fathom",
  googleanalytics4: "google-analytics",
  ga4: "google-analytics",
  hotjarinsights: "hotjar",
  fullstorycom: "fullstory",
  logrocketcom: "logrocket",
  heapanalytics: "heap",

  // Monitoring
  sentryio: "sentry",
  "uptime robot": "uptimerobot",
  uptimerobot: "uptimerobot",
  "grafana cloud": "grafana",
  grafanaoss: "grafana",
  datadoghq: "datadog",
  newrelicapm: "newrelic",
  dynatraceapm: "dynatrace",
  honeycombio: "honeycomb",
  splunkenterprise: "splunk",
  jaegertracing: "jaeger",
  jaegerio: "jaeger",
  zipkinio: "zipkin",

  // Security
  cloudflarewaf: "cloudflare-waf",
  awswaffirewall: "aws-waf",
  snyksecurity: "snyk",
  sonarqubeorg: "sonarqube",
  trivyscan: "trivy",
  checkmarxscan: "checkmarx",
  veracodesecurity: "veracode",
  authy2fa: "authy",
  "1passwordsecrets": "1password",
  onepassworddev: "1password",
  bitwardenpass: "bitwarden",
  crowdstrikefalcon: "crowdstrike",
  oktasecurity: "okta-security",
  burpsuitepro: "burp-suite",
  owaspzapscan: "owasp-zap",

  // Testing
  cypressio: "cypress",
  cypressjs: "cypress",
  playwrightdev: "playwright",
  seleniumwebdriver: "selenium",
  jestjs: "jest",
  vitestdev: "vitest",
  mochajs: "mocha",
  k6io: "k6",
  k6load: "k6",
  artilleryio: "artillery",
  storybookjs: "storybook",
  chromaticcom: "chromatic",
  percyio: "percy",
  detoxtesting: "detox",
  appiumio: "appium",
  gatlingio: "gatling",
  locustload: "locust",

  // Storage
  amazons3: "s3",
  "amazon s3": "s3",
  gcsbucket: "gcs",
  googlecloudstorage: "gcs",
  "google cloud storage": "gcs",
  azureblob: "azure-blob",
  azurestorage: "azure-blob",
  cloudflarer2: "cloudflare-r2",
  miniostorage: "minio",
  backblazeb2: "backblaze",
  wasabis3: "wasabi",
  dropboxapi: "dropbox",
  boxcloud: "box",

  // Compute
  awslambda: "lambda",
  "aws lambda": "lambda",
  cloudrun: "cloud-run",
  googlecloudrun: "cloud-run",
  azurefunctions: "azure-functions",
  "azure functions": "azure-functions",
  cloudflareworkers: "cloudflare-workers",
  awsecs: "ecs",
  "aws ecs": "ecs",
  amazonelasticcontainerservice: "ecs",
  awseks: "eks",
  "aws eks": "eks",
  amazoneks: "eks",
  ekscluster: "eks",
  awsfargate: "fargate",
  ecsfargate: "fargate",
  amazonec2: "ec2",
  amazonelasticcomputecloud: "ec2",
  gkecluster: "gke",
  googlekubernetesengine: "gke",
  akscluster: "aks",
  azurekubernetesservice: "aks",

  // CI/CD
  githubactions: "github-actions",
  githubci: "github-actions",
  gitlabcicd: "gitlab-ci",
  gitlabci: "gitlab-ci",
  jenkinsio: "jenkins",
  circlecici: "circleci",
  travisci: "travis",
  argocd: "argocd",
  argoproj: "argocd",
  spinnakerio: "spinnaker",
  azuredevops: "azure-devops",
  azdo: "azure-devops",

  // DevOps
  dockercontainer: "docker",
  k8s: "kubernetes",
  kubernetescncf: "kubernetes",
  terraformiac: "terraform",
  hashicorptf: "terraform",
  ansibleplaybook: "ansible",
  redhatansible: "ansible",
  nginxproxy: "nginx",
  apachehttpd: "apache",
  konggateway: "kong",
  konghq: "kong",
  traefikproxy: "traefik",
  containo: "traefik",
  envoyproxy: "envoy",
  consulhashi: "consul",
  hashicorpconsul: "consul",
  vaulthashi: "vault",
  hashicorpvault: "vault",
  istioservice: "istio",
  istioio: "istio",
  linkerdproxy: "linkerd",
  linkerdio: "linkerd",

  // AWS Services
  awsapigateway: "aws-api-gateway",
  amazonapigateway: "aws-api-gateway",
  awsappmesh: "aws-app-mesh",
  appmeshaws: "aws-app-mesh",
  awssync: "aws-app-sync",
  appsyncaws: "aws-app-sync",
  awsbatch: "aws-batch",
  batchaws: "aws-batch",
  awscloudformation: "aws-cloudformation",
  cloudformationaws: "aws-cloudformation",
  awscloudfront: "aws-cloudfront",
  cloudfrontcdn: "aws-cloudfront",
  awscloudtrail: "aws-cloudtrail",
  cloudtrailaws: "aws-cloudtrail",
  awscloudwatch: "aws-cloudwatch",
  cloudwatchlogs: "aws-cloudwatch",
  awscodebuild: "aws-codebuild",
  codebuildaws: "aws-codebuild",
  awscodecommit: "aws-codecommit",
  codecommitaws: "aws-codecommit",
  awscodedeploy: "aws-codedeploy",
  codedeployaws: "aws-codedeploy",
  awscodepipeline: "aws-codepipeline",
  codepipelineaws: "aws-codepipeline",
  awsconfig: "aws-config",
  configaws: "aws-config",
  awsdocumentdb: "aws-documentdb",
  documentdbaws: "aws-documentdb",
  awselasticache: "aws-elasticache",
  elasticacheredis: "aws-elasticache",
  awselasticsearch: "aws-elasticsearch",
  opensearchaws: "aws-opensearch",
  awseventbridge: "aws-eventbridge",
  eventbridgeaws: "aws-eventbridge",
  awsglue: "aws-glue",
  glueaws: "aws-glue",
  awsiam: "aws-iam",
  iamaws: "aws-iam",
  awskinesis: "aws-kinesis",
  kinesisaws: "aws-kinesis",
  awskms: "aws-kms",
  kmsaws: "aws-kms",
  awslakeformation: "aws-lake-formation",
  lakeformationaws: "aws-lake-formation",
  awsmq: "aws-mq",
  mqaws: "aws-mq",
  awsmsk: "aws-msk",
  msKaws: "aws-msk",
  awsneptune: "aws-neptune",
  neptuneaws: "aws-neptune",
  awsopensearch: "aws-opensearch",
  awspinpoint: "aws-pinpoint",
  pinpointaws: "aws-pinpoint",
  awsquicksight: "aws-quicksight",
  quicksightaws: "aws-quicksight",
  awsrds: "aws-rds",
  rdsaws: "aws-rds",
  awsredshift: "aws-redshift",
  redshiftaws: "aws-redshift",
  awsroute53: "aws-route53",
  route53aws: "aws-route53",
  awssagemaker: "aws-sagemaker",
  sagemakeraws: "aws-sagemaker",
  awssecretsmanager: "aws-secrets-manager",
  secretsmanageraws: "aws-secrets-manager",
  awsshield: "aws-shield",
  shieldaws: "aws-shield",
  awssnowball: "aws-snowball",
  snowballaws: "aws-snowball",
  awssns: "aws-sns",
  snsaws: "aws-sns",
  awssqs: "aws-sqs",
  sqsaws: "aws-sqs",
  awsstepfunctions: "aws-step-functions",
  stepfunctionsaws: "aws-step-functions",
  awstextract: "aws-textract",
  textractaws: "aws-textract",
  awstransitgateway: "aws-transit-gateway",
  transitgatewayaws: "aws-transit-gateway",
  awsvpc: "aws-vpc",
  vpcaws: "aws-vpc",
  awsxray: "aws-xray",
  xrayaws: "aws-xray",

  // GCP Services
  gcpappengine: "gcp-app-engine",
  appenginegcp: "gcp-app-engine",
  gcpbigquery: "gcp-bigquery",
  bigquerygcp: "gcp-bigquery",
  gcpbigtable: "gcp-bigtable",
  bigtablegcp: "gcp-bigtable",
  gcpbuild: "gcp-build",
  cloudbuildgcp: "gcp-build",
  gcpcdn: "gcp-cdn",
  cloudcdngcp: "gcp-cdn",
  gcpcomposer: "gcp-composer",
  composercloud: "gcp-composer",
  gcpdataflow: "gcp-dataflow",
  dataflowgcp: "gcp-dataflow",
  gcpdatafusion: "gcp-datafusion",
  datafusiongcp: "gcp-datafusion",
  gcpdataproc: "gcp-dataproc",
  dataprocgcp: "gcp-dataproc",
  gcpdns: "gcp-dns",
  dnscloud: "gcp-dns",
  gcpendpoints: "gcp-endpoints",
  endpointscloud: "gcp-endpoints",
  gcpeventarc: "gcp-eventarc",
  eventarcgcp: "gcp-eventarc",
  gcpfilestore: "gcp-filestore",
  filestorecloud: "gcp-filestore",
  gcpfirestore: "gcp-firestore",
  firestorecloud: "gcp-firestore",
  gcpfunctions: "gcp-functions",
  functionscloud: "gcp-functions",
  gcpiam: "gcp-iam",
  iamcloud: "gcp-iam",
  gcpiot: "gcp-iot",
  iotcloud: "gcp-iot",
  gcpkms: "gcp-kms",
  kmscloud: "gcp-kms",
  gcploadbalancing: "gcp-load-balancing",
  loadbalancingcloud: "gcp-load-balancing",
  gcplogging: "gcp-logging",
  loggingcloud: "gcp-logging",
  gcpmemorystore: "gcp-memorystore",
  memorystorecloud: "gcp-memorystore",
  gcpmonitoring: "gcp-monitoring",
  monitoringcloud: "gcp-monitoring",
  gcpnat: "gcp-nat",
  natcloud: "gcp-nat",
  gcppubsub: "gcp-pubsub",
  pubsubcloud: "gcp-pubsub",
  gcprun: "gcp-run",
  runcloud: "gcp-run",
  gcpscheduler: "gcp-scheduler",
  schedulercloud: "gcp-scheduler",
  gcpsecretmanager: "gcp-secret-manager",
  secretmanagercloud: "gcp-secret-manager",
  gcpspanner: "gcp-spanner",
  spannercloud: "gcp-spanner",
  gcpspeech: "gcp-speech",
  speechcloud: "gcp-speech",
  gcpsql: "gcp-sql",
  sqlcloud: "gcp-sql",
  gcpstorage: "gcp-storage",
  storagecloud: "gcp-storage",
  gcptasks: "gcp-tasks",
  taskscloud: "gcp-tasks",
  gcptpu: "gcp-tpu",
  tpucloud: "gcp-tpu",
  gcptrace: "gcp-trace",
  tracecloud: "gcp-trace",
  gcptranslate: "gcp-translate",
  translatecloud: "gcp-translate",
  gcpvideo: "gcp-video",
  videocloud: "gcp-video",
  gcpvision: "gcp-vision",
  visioncloud: "gcp-vision",
  gcpvpc: "gcp-vpc",
  vpccloud: "gcp-vpc",
  gcpworkflows: "gcp-workflows",
  workflowscloud: "gcp-workflows",
};

/**
 * Normalize a tech name to its ecosystem ID
 * Uses exact match, alias lookup, and fuzzy matching
 */
export function normalizeTechName(input: string): string | undefined {
  if (!input) return undefined;

  const normalized = input.toLowerCase().trim();

  // 1. Direct ID match
  const directMatch = TECH_ECOSYSTEM.find((t) => t.id === normalized);
  if (directMatch) return directMatch.id;

  // 2. Alias lookup
  if (TECH_ALIASES[normalized]) {
    return TECH_ALIASES[normalized];
  }

  // 3. Label match (case-insensitive)
  const labelMatch = TECH_ECOSYSTEM.find(
    (t) => t.label.toLowerCase() === normalized,
  );
  if (labelMatch) return labelMatch.id;

  // 4. Partial match (contains)
  const partialMatch = TECH_ECOSYSTEM.find(
    (t) =>
      normalized.includes(t.id) || normalized.includes(t.label.toLowerCase()),
  );
  if (partialMatch) return partialMatch.id;

  // 5. Reverse partial (ID or label contained in input)
  for (const tech of TECH_ECOSYSTEM) {
    if (
      tech.id.includes(normalized) ||
      tech.label.toLowerCase().includes(normalized)
    ) {
      return tech.id;
    }
  }

  return undefined;
}

/**
 * Get full tech item from a label or ID
 */
export function getTechFromLabel(labelOrId: string): TechItem | undefined {
  const id = normalizeTechName(labelOrId);
  if (!id) return undefined;
  return TECH_ECOSYSTEM.find((t) => t.id === id);
}

/**
 * Enrich node data with tech information
 */
export function enrichNodeWithTech(
  nodeData: Record<string, unknown> & { tech?: string; label?: string },
): Record<string, unknown> {
  if (!nodeData.tech && !nodeData.label) return nodeData;

  const techIdentifier = (nodeData.tech || nodeData.label) as string;
  const tech = getTechFromLabel(techIdentifier);

  if (tech) {
    return {
      ...nodeData,
      tech: tech.id,
      techLabel: tech.label,
      techIcon: tech.icon,
      techCategory: tech.category,
    };
  }

  return nodeData;
}

/**
 * Enrich multiple nodes with tech information
 */
export function enrichNodesWithTech(
  nodes: Array<Record<string, unknown> & { data?: Record<string, unknown> }>,
): Array<Record<string, unknown>> {
  return nodes.map((node) => {
    if (node.data) {
      return {
        ...node,
        data: enrichNodeWithTech(node.data),
      };
    }
    return node;
  });
}
