export type TechCategory =
  | "ai"
  | "auth"
  | "automation"
  | "aws"
  | "backend"
  | "cache"
  | "cicd"
  | "cloud"
  | "cms"
  | "compute"
  | "data"
  | "database"
  | "desktop"
  | "devops"
  | "frontend"
  | "gcp"
  | "messaging"
  | "mobile"
  | "monitoring"
  | "payment"
  | "queue"
  | "search"
  | "security"
  | "storage"
  | "testing"
  | "tooling"
  | "vector-db";

export interface TechItem {
  id: string;
  label: string;
  icon: string;
  category: TechCategory;
  defaultType?: string;
  aliases?: string[];
  keywords?: string[];
  description?: string;
  tier?: "common" | "niche";
}

export const TECH_ECOSYSTEM: TechItem[] = [
  {
    id: "agno",
    label: "Agno",
    icon: "lucide:network",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "ai-sdk-rsc",
    label: "AI SDK RSC",
    icon: "logos:vercel-icon",
    category: "ai",
    defaultType: "ai-sdk",
  },
  {
    id: "ai-sdk-ui",
    label: "AI SDK UI",
    icon: "logos:vercel-icon",
    category: "ai",
    defaultType: "ai-sdk",
  },
  {
    id: "ai21",
    label: "AI21 Labs",
    icon: "logos:ai21",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "anthropic",
    label: "Anthropic",
    icon: "logos:anthropic-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "anyscale",
    label: "Anyscale",
    icon: "logos:anyscale",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "atomic-agents",
    label: "Atomic Agents",
    icon: "lucide:atom",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "autogen",
    label: "AutoGen",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "bedrock",
    label: "AWS Bedrock",
    icon: "logos:aws",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "aws-bedrock",
    label: "AWS Bedrock",
    icon: "logos:aws",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "azure-openai",
    label: "Azure OpenAI",
    icon: "logos:azure-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "banana-dev",
    label: "Banana.dev",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "baseten",
    label: "Baseten",
    icon: "logos:baseten",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "beeai-framework",
    label: "BeeAI Framework",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "browser-use",
    label: "Browser Use",
    icon: "lucide:globe",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "burr",
    label: "Burr",
    icon: "lucide:workflow",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "camel-ai",
    label: "CAMEL AI",
    icon: "lucide:users",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "cerebras",
    label: "Cerebras",
    icon: "lucide:cpu",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "anthropic-claude",
    label: "Claude",
    icon: "logos:anthropic-icon",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "claude-4",
    label: "Claude 4",
    icon: "logos:anthropic",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "codellama",
    label: "CodeLlama",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "cohere",
    label: "Cohere",
    icon: "logos:cohere",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "cohere-rerank",
    label: "Cohere Rerank",
    icon: "logos:cohere",
    category: "ai",
    defaultType: "rerank",
  },
  {
    id: "command-r",
    label: "Command R",
    icon: "logos:cohere",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "continue",
    label: "Continue",
    icon: "logos:continue",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "crewai",
    label: "CrewAI",
    icon: "logos:crewai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "dashscope",
    label: "DashScope",
    icon: "logos:alibaba-cloud",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "deepeval",
    label: "DeepEval",
    icon: "lucide:clipboard-check",
    category: "ai",
    defaultType: "eval",
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    icon: "logos:deepinfra",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    icon: "logos:deepseek",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "deepseek-v3",
    label: "DeepSeek v3",
    icon: "arcticons:deepseek",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "deepseek-v4",
    label: "DeepSeek V4",
    icon: "logos:deepseek",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "dify",
    label: "Dify",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-builder",
  },
  {
    id: "dolphin",
    label: "Dolphin",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "dspy",
    label: "DSPy",
    icon: "lucide:brain-circuit",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "fal-ai",
    label: "fal.ai",
    icon: "lucide:sparkles",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "falcon",
    label: "Falcon",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    icon: "logos:fireworks",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "flashrank",
    label: "FlashRank",
    icon: "lucide:list-filter",
    category: "ai",
    defaultType: "rerank",
  },
  {
    id: "flowise",
    label: "Flowise",
    icon: "lucide:workflow",
    category: "ai",
    defaultType: "ai-builder",
  },
  {
    id: "gemini-pro",
    label: "Gemini 1.5 Pro",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gemini-2-5",
    label: "Gemini 2.5",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gemma",
    label: "Gemma",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "google-adk",
    label: "Google Agent Development Kit",
    icon: "logos:google-cloud",
    category: "ai",
    defaultType: "ai-agent",
  },
  {
    id: "google-a2a",
    label: "Google Agent2Agent",
    icon: "logos:google-cloud",
    category: "ai",
    defaultType: "protocol",
  },
  {
    id: "google-gemini",
    label: "Google Gemini",
    icon: "logos:google-gemini",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "gpt-5",
    label: "GPT-5",
    icon: "logos:openai",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "gpt4all",
    label: "GPT4All",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "groq",
    label: "Groq",
    icon: "logos:groq",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "guardrails-ai",
    label: "Guardrails AI",
    icon: "lucide:shield-check",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "guidance",
    label: "Guidance",
    icon: "lucide:braces",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "haystack",
    label: "Haystack",
    icon: "logos:haystack",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "helicone",
    label: "Helicone",
    icon: "lucide:activity",
    category: "ai",
    defaultType: "observability",
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    icon: "logos:huggingface-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "humanloop",
    label: "Humanloop",
    icon: "lucide:repeat",
    category: "ai",
    defaultType: "eval",
  },
  {
    id: "instructor",
    label: "Instructor",
    icon: "lucide:file-json",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "jan",
    label: "Jan",
    icon: "logos:jan",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "jina-ai",
    label: "Jina AI",
    icon: "lucide:search",
    category: "ai",
    defaultType: "embedding",
  },
  {
    id: "koboldcpp",
    label: "KoboldCPP",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "langchain",
    label: "LangChain",
    icon: "logos:langchain",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "langchain-mcp-adapters",
    label: "LangChain MCP Adapters",
    icon: "logos:langchain",
    category: "ai",
    defaultType: "protocol",
  },
  {
    id: "langflow",
    label: "Langflow",
    icon: "lucide:workflow",
    category: "ai",
    defaultType: "ai-builder",
  },
  {
    id: "langgraph",
    label: "LangGraph",
    icon: "logos:langchain",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "litellm",
    label: "LiteLLM",
    icon: "logos:litellm",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "llama",
    label: "Llama",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "llama-4",
    label: "Llama 4",
    icon: "logos:meta",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "llamacpp",
    label: "llama.cpp",
    icon: "logos:llamacpp",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "llamaindex",
    label: "LlamaIndex",
    icon: "logos:llamaindex",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "llama-parse",
    label: "LlamaParse",
    icon: "lucide:file-search",
    category: "ai",
    defaultType: "rag",
  },
  {
    id: "lm-studio",
    label: "LM Studio",
    icon: "logos:lmstudio",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "localai",
    label: "LocalAI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "marvin",
    label: "Marvin",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "mastra",
    label: "Mastra",
    icon: "logos:mastra",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "mem0",
    label: "Mem0",
    icon: "lucide:database",
    category: "ai",
    defaultType: "memory",
  },
  {
    id: "memgpt",
    label: "MemGPT",
    icon: "lucide:database",
    category: "ai",
    defaultType: "memory",
  },
  {
    id: "mistral-7b",
    label: "Mistral 7B",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "mistral",
    label: "Mistral AI",
    icon: "logos:mistral-ai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "mistral-large",
    label: "Mistral Large",
    icon: "logos:mistral-ai",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "mixtral",
    label: "Mixtral",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "modal",
    label: "Modal",
    icon: "lucide:cloud",
    category: "ai",
    defaultType: "compute",
  },
  {
    id: "mcp",
    label: "Model Context Protocol",
    icon: "logos:anthropic-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "mpt",
    label: "MPT",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "neural-chat",
    label: "Neural Chat",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "novita-ai",
    label: "Novita AI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "nvidia-nim",
    label: "NVIDIA NIM",
    icon: "logos:nvidia",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "octoml",
    label: "OctoML",
    icon: "logos:octoml",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "ollama",
    label: "Ollama",
    icon: "logos:ollama",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "openai",
    label: "OpenAI",
    icon: "logos:openai-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "openai-agents-sdk",
    label: "OpenAI Agents SDK",
    icon: "logos:openai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "openai-o1",
    label: "OpenAI o1",
    icon: "logos:openai-icon",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "openai-responses-api",
    label: "OpenAI Responses API",
    icon: "logos:openai-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "openchat",
    label: "OpenChat",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "openpipe",
    label: "OpenPipe",
    icon: "lucide:pipe",
    category: "ai",
    defaultType: "fine-tuning",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    icon: "logos:openrouter",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "outlines",
    label: "Outlines",
    icon: "lucide:braces",
    category: "ai",
    defaultType: "ai-framework",
  },
  {
    id: "perplexity",
    label: "Perplexity",
    icon: "logos:perplexity",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "phi",
    label: "Phi",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "portkey",
    label: "Portkey",
    icon: "lucide:route",
    category: "ai",
    defaultType: "gateway",
  },
  {
    id: "predibase",
    label: "Predibase",
    icon: "logos:predibase",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "promptflow",
    label: "Prompt Flow",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "promptfoo",
    label: "Promptfoo",
    icon: "lucide:test-tube",
    category: "ai",
    defaultType: "eval",
  },
  {
    id: "pydantic-ai",
    label: "Pydantic AI",
    icon: "logos:pydantic",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "qwen",
    label: "Qwen",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "qwen3",
    label: "Qwen 3",
    icon: "logos:alibaba-cloud",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "ragas",
    label: "Ragas",
    icon: "lucide:clipboard-check",
    category: "ai",
    defaultType: "eval",
  },
  {
    id: "ragflow",
    label: "RAGFlow",
    icon: "lucide:search",
    category: "ai",
    defaultType: "rag",
  },
  {
    id: "replicate",
    label: "Replicate",
    icon: "logos:replicate",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "rerankers",
    label: "rerankers",
    icon: "lucide:list-filter",
    category: "ai",
    defaultType: "rerank",
  },
  {
    id: "runpod",
    label: "RunPod",
    icon: "lucide:server",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "sambanova",
    label: "SambaNova",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "semantic-kernel",
    label: "Semantic Kernel",
    icon: "logos:microsoft",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "starcoder",
    label: "StarCoder",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "tabby",
    label: "Tabby",
    icon: "logos:tabby",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "text-generation-webui",
    label: "Text Generation WebUI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "together",
    label: "Together AI",
    icon: "logos:together-ai",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "unstructured",
    label: "Unstructured",
    icon: "lucide:file-text",
    category: "ai",
    defaultType: "rag",
  },
  {
    id: "vercel-ai-gateway",
    label: "Vercel AI Gateway",
    icon: "logos:vercel-icon",
    category: "ai",
    defaultType: "gateway",
  },
  {
    id: "ai-sdk",
    label: "Vercel AI SDK",
    icon: "logos:vercel-icon",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "vercel-ai-sdk",
    label: "Vercel AI SDK",
    icon: "logos:vercel-icon",
    category: "ai",
    defaultType: "ai-sdk",
  },
  {
    id: "vertex-ai",
    label: "Vertex AI",
    icon: "logos:google-cloud",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "vllm",
    label: "vLLM",
    icon: "logos:vllm",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "voyage-ai",
    label: "Voyage AI",
    icon: "lucide:search",
    category: "ai",
    defaultType: "embedding",
  },
  {
    id: "wizardcoder",
    label: "WizardCoder",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "xai",
    label: "xAI",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai",
  },
  {
    id: "yi",
    label: "Yi",
    icon: "lucide:bot",
    category: "ai",
    defaultType: "ai-model",
  },
  {
    id: "zep",
    label: "Zep",
    icon: "lucide:database",
    category: "ai",
    defaultType: "memory",
  },
  {
    id: "authjs",
    label: "Auth.js",
    icon: "logos:nextauth",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "auth0",
    label: "Auth0",
    icon: "logos:auth0",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "authelia",
    label: "Authelia",
    icon: "logos:authelia",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "authentik",
    label: "Authentik",
    icon: "logos:authentik",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "cognito",
    label: "AWS Cognito",
    icon: "logos:aws-cognito",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "aws-cognito",
    label: "AWS Cognito",
    icon: "logos:aws",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "azure-ad",
    label: "Azure AD",
    icon: "logos:azure-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "better-auth",
    label: "Better Auth",
    icon: "logos:better-auth",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "casdoor",
    label: "Casdoor",
    icon: "logos:casdoor",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "clerk",
    label: "Clerk",
    icon: "logos:clerk",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "descope",
    label: "Descope",
    icon: "lucide:shield-check",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "firebase-auth",
    label: "Firebase Auth",
    icon: "logos:firebase",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "fusionauth",
    label: "FusionAuth",
    icon: "logos:fusionauth",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "jwt",
    label: "JWT",
    icon: "logos:jwt",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "keycloak",
    label: "Keycloak",
    icon: "logos:keycloak",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "kinde",
    label: "Kinde",
    icon: "lucide:shield-check",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "logto",
    label: "Logto",
    icon: "logos:logto",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "lucia-auth",
    label: "Lucia Auth",
    icon: "lucide:shield-check",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "nextauth",
    label: "NextAuth.js",
    icon: "logos:nextjs-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "oauth2",
    label: "OAuth 2.0",
    icon: "logos:oauth",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "okta",
    label: "Okta",
    icon: "logos:okta",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "onelogin",
    label: "OneLogin",
    icon: "logos:onelogin",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "openid-connect",
    label: "OpenID Connect",
    icon: "logos:openid",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "ory",
    label: "Ory",
    icon: "logos:ory",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "stytch",
    label: "Stytch",
    icon: "lucide:shield-check",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "supabase-auth",
    label: "Supabase Auth",
    icon: "logos:supabase-icon",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "supertokens",
    label: "SuperTokens",
    icon: "logos:supertokens",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "workos",
    label: "WorkOS",
    icon: "logos:workos",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "zitadel",
    label: "Zitadel",
    icon: "logos:zitadel",
    category: "auth",
    defaultType: "auth",
  },
  {
    id: "boomi",
    label: "Boomi",
    icon: "logos:boomi",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "huginn",
    label: "Huginn",
    icon: "lucide:bot",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "ifttt",
    label: "IFTTT",
    icon: "logos:ifttt",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "make",
    label: "Make",
    icon: "logos:make",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "mulesoft",
    label: "MuleSoft",
    icon: "logos:mulesoft",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "n8n",
    label: "n8n",
    icon: "logos:n8n",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "node-red",
    label: "Node-RED",
    icon: "logos:node-red",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "tray",
    label: "Tray.io",
    icon: "logos:tray",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "workato",
    label: "Workato",
    icon: "logos:workato",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "zapier",
    label: "Zapier",
    icon: "logos:zapier",
    category: "automation",
    defaultType: "automation",
  },
  {
    id: "aws-api-gateway",
    label: "AWS API Gateway",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-app-mesh",
    label: "AWS App Mesh",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-app-sync",
    label: "AWS AppSync",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-batch",
    label: "AWS Batch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "compute",
  },
  {
    id: "aws-cloudformation",
    label: "AWS CloudFormation",
    icon: "logos:aws",
    category: "aws",
    defaultType: "service",
  },
  {
    id: "aws-cloudfront",
    label: "AWS CloudFront",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-cloudtrail",
    label: "AWS CloudTrail",
    icon: "logos:aws",
    category: "aws",
    defaultType: "monitoring",
  },
  {
    id: "aws-cloudwatch",
    label: "AWS CloudWatch",
    icon: "logos:aws-cloudwatch",
    category: "aws",
    defaultType: "monitoring",
  },
  {
    id: "aws-codebuild",
    label: "AWS CodeBuild",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codecommit",
    label: "AWS CodeCommit",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codedeploy",
    label: "AWS CodeDeploy",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-codepipeline",
    label: "AWS CodePipeline",
    icon: "logos:aws",
    category: "aws",
    defaultType: "cicd",
  },
  {
    id: "aws-config",
    label: "AWS Config",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-documentdb",
    label: "AWS DocumentDB",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-elasticache",
    label: "AWS ElastiCache",
    icon: "logos:aws-elasticache",
    category: "aws",
    defaultType: "cache",
  },
  {
    id: "aws-elasticsearch",
    label: "AWS Elasticsearch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-eventbridge",
    label: "AWS EventBridge",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-glue",
    label: "AWS Glue",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-iam",
    label: "AWS IAM",
    icon: "logos:aws-iam",
    category: "aws",
    defaultType: "auth",
  },
  {
    id: "aws-kinesis",
    label: "AWS Kinesis",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-kms",
    label: "AWS KMS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-lake-formation",
    label: "AWS Lake Formation",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-lambda",
    label: "AWS Lambda",
    icon: "logos:aws-lambda",
    category: "aws",
    defaultType: "function",
  },
  {
    id: "aws-mq",
    label: "AWS MQ",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-msk",
    label: "AWS MSK",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-neptune",
    label: "AWS Neptune",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-opensearch",
    label: "AWS OpenSearch",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-pinpoint",
    label: "AWS Pinpoint",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-quicksight",
    label: "AWS QuickSight",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-rds",
    label: "AWS RDS",
    icon: "logos:aws-rds",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-redshift",
    label: "AWS Redshift",
    icon: "logos:aws",
    category: "aws",
    defaultType: "database",
  },
  {
    id: "aws-route53",
    label: "AWS Route 53",
    icon: "logos:aws",
    category: "aws",
    defaultType: "gateway",
  },
  {
    id: "aws-sagemaker",
    label: "AWS SageMaker",
    icon: "logos:aws",
    category: "aws",
    defaultType: "ai",
  },
  {
    id: "aws-secrets-manager",
    label: "AWS Secrets Manager",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-shield",
    label: "AWS Shield",
    icon: "logos:aws",
    category: "aws",
    defaultType: "security",
  },
  {
    id: "aws-snowball",
    label: "AWS Snowball",
    icon: "logos:aws",
    category: "aws",
    defaultType: "storage",
  },
  {
    id: "aws-sns",
    label: "AWS SNS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "messaging",
  },
  {
    id: "aws-sqs",
    label: "AWS SQS",
    icon: "logos:aws",
    category: "aws",
    defaultType: "queue",
  },
  {
    id: "aws-step-functions",
    label: "AWS Step Functions",
    icon: "logos:aws",
    category: "aws",
    defaultType: "automation",
  },
  {
    id: "aws-textract",
    label: "AWS Textract",
    icon: "logos:aws",
    category: "aws",
    defaultType: "ai",
  },
  {
    id: "aws-transit-gateway",
    label: "AWS Transit Gateway",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-vpc",
    label: "AWS VPC",
    icon: "logos:aws",
    category: "aws",
    defaultType: "aws",
  },
  {
    id: "aws-xray",
    label: "AWS X-Ray",
    icon: "logos:aws",
    category: "aws",
    defaultType: "monitoring",
  },
  {
    id: "actix",
    label: "Actix",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "adonisjs",
    label: "AdonisJS",
    icon: "logos:adonisjs-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "dotnet",
    label: "ASP.NET Core",
    icon: "logos:dotnet",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "axum",
    label: "Axum",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "bun",
    label: "Bun",
    icon: "logos:bun",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "deno",
    label: "Deno",
    icon: "logos:deno",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "django",
    label: "Django",
    icon: "logos:django",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "echo",
    label: "Echo",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "effect",
    label: "Effect",
    icon: "lucide:sparkles",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elixir",
    label: "Elixir",
    icon: "logos:elixir",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elysia",
    label: "Elysia",
    icon: "logos:elysia",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elysia-eden",
    label: "Elysia Eden",
    icon: "logos:elysia",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "elysiajs",
    label: "ElysiaJS",
    icon: "logos:elysia",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "express",
    label: "Express",
    icon: "logos:express",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fastapi",
    label: "FastAPI",
    icon: "logos:fastapi",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fastify",
    label: "Fastify",
    icon: "logos:fastify",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "fiber",
    label: "Fiber",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "flask",
    label: "Flask",
    icon: "logos:flask",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "gin",
    label: "Gin",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "go",
    label: "Go",
    icon: "logos:go",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "graphql",
    label: "GraphQL",
    icon: "logos:graphql",
    category: "backend",
    defaultType: "service",
  },
  {
    id: "grpc",
    label: "gRPC",
    icon: "logos:grpc",
    category: "backend",
    defaultType: "service",
  },
  {
    id: "h3",
    label: "h3",
    icon: "lucide:server",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "hattip",
    label: "Hattip",
    icon: "carbon:http",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "hono",
    label: "Hono",
    icon: "logos:hono",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "hono-rpc",
    label: "Hono RPC",
    icon: "logos:hono",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "java",
    label: "Java",
    icon: "logos:java",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "laravel",
    label: "Laravel",
    icon: "logos:laravel",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "nestjs",
    label: "NestJS",
    icon: "logos:nestjs",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "nitro",
    label: "Nitro",
    icon: "logos:nitro-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "nodejs",
    label: "Node.js",
    icon: "logos:nodejs-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "openapi",
    label: "OpenAPI",
    icon: "logos:openapi-icon",
    category: "backend",
    defaultType: "service",
  },
  {
    id: "orpc",
    label: "oRPC",
    icon: "lucide:workflow",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "partykit",
    label: "PartyKit",
    icon: "lucide:party-popper",
    category: "backend",
    defaultType: "server",
  },
  {
    id: "phoenix",
    label: "Phoenix",
    icon: "logos:phoenix-framework",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "php",
    label: "PHP",
    icon: "logos:php",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "python",
    label: "Python",
    icon: "logos:python",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "ruby",
    label: "Ruby",
    icon: "logos:ruby",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "rails",
    label: "Ruby on Rails",
    icon: "logos:ruby-on-rails",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "rust",
    label: "Rust",
    icon: "logos:rust",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "spring-boot",
    label: "Spring Boot",
    icon: "logos:spring-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "spring",
    label: "Spring Boot",
    icon: "logos:spring-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "symfony",
    label: "Symfony",
    icon: "logos:symfony",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "trpc",
    label: "tRPC",
    icon: "logos:trpc",
    category: "backend",
    defaultType: "service",
  },
  {
    id: "val-town",
    label: "Val Town",
    icon: "carbon:function",
    category: "backend",
    defaultType: "function",
  },
  {
    id: "workerd",
    label: "workerd (Cloudflare)",
    icon: "logos:cloudflare-workers-icon",
    category: "backend",
    defaultType: "backend",
  },
  {
    id: "memcached",
    label: "Memcached",
    icon: "logos:memcached",
    category: "cache",
    defaultType: "cache",
  },
  {
    id: "redis",
    label: "Redis",
    icon: "logos:redis",
    category: "cache",
    defaultType: "cache",
  },
  {
    id: "upstash-redis",
    label: "Upstash Redis",
    icon: "logos:upstash",
    category: "cache",
    defaultType: "cache",
  },
  {
    id: "valkey",
    label: "Valkey",
    icon: "logos:redis",
    category: "cache",
    defaultType: "cache",
  },
  {
    id: "argo-cd",
    label: "Argo CD",
    icon: "logos:argo-icon",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "argocd",
    label: "ArgoCD",
    icon: "logos:argo-icon",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "azure-devops",
    label: "Azure DevOps",
    icon: "logos:azure-devops",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "circleci",
    label: "CircleCI",
    icon: "logos:circleci",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "github-actions",
    label: "GitHub Actions",
    icon: "logos:github-actions",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "gitlab-ci",
    label: "GitLab CI",
    icon: "logos:gitlab",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "jenkins",
    label: "Jenkins",
    icon: "logos:jenkins",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "spinnaker",
    label: "Spinnaker",
    icon: "logos:spinnaker",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "travis",
    label: "Travis CI",
    icon: "logos:travis-ci",
    category: "cicd",
    defaultType: "cicd",
  },
  {
    id: "aws",
    label: "AWS",
    icon: "logos:aws",
    category: "cloud",
    defaultType: "gateway",
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    icon: "logos:cloudflare",
    category: "cloud",
    defaultType: "gateway",
  },
  {
    id: "coolify",
    label: "Coolify",
    icon: "logos:coolify",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "digitalocean",
    label: "DigitalOcean",
    icon: "logos:digital-ocean",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "fly-io",
    label: "Fly.io",
    icon: "logos:fly-io",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "fly",
    label: "Fly.io",
    icon: "logos:fly-io",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "gcp",
    label: "Google Cloud",
    icon: "logos:google-cloud",
    category: "cloud",
    defaultType: "gateway",
  },
  {
    id: "heroku",
    label: "Heroku",
    icon: "logos:heroku-icon",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "hetzner",
    label: "Hetzner",
    icon: "logos:hetzner",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "linode",
    label: "Linode / Akamai",
    icon: "logos:akamai",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "azure",
    label: "Microsoft Azure",
    icon: "logos:microsoft-azure",
    category: "cloud",
    defaultType: "gateway",
  },
  {
    id: "netlify",
    label: "Netlify",
    icon: "logos:netlify-icon",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "ovh",
    label: "OVH",
    icon: "logos:ovh",
    category: "cloud",
    defaultType: "cloud",
  },
  {
    id: "railway",
    label: "Railway",
    icon: "logos:railway",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "render",
    label: "Render",
    icon: "logos:render",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "vercel",
    label: "Vercel",
    icon: "logos:vercel-icon",
    category: "cloud",
    defaultType: "cicd",
  },
  {
    id: "contentful",
    label: "Contentful",
    icon: "logos:contentful",
    category: "cms",
    defaultType: "database",
  },
  {
    id: "directus",
    label: "Directus",
    icon: "logos:directus",
    category: "cms",
    defaultType: "database",
  },
  {
    id: "payload-cms",
    label: "Payload CMS",
    icon: "logos:payload-cms",
    category: "cms",
    defaultType: "database",
  },
  {
    id: "sanity",
    label: "Sanity",
    icon: "logos:sanity",
    category: "cms",
    defaultType: "database",
  },
  {
    id: "strapi",
    label: "Strapi",
    icon: "logos:strapi-icon",
    category: "cms",
    defaultType: "database",
  },
  {
    id: "ec2",
    label: "Amazon EC2",
    icon: "logos:aws-ec2",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "ecs",
    label: "AWS ECS",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "eks",
    label: "AWS EKS",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "fargate",
    label: "AWS Fargate",
    icon: "logos:aws",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "lambda",
    label: "AWS Lambda",
    icon: "logos:aws-lambda",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "azure-functions",
    label: "Azure Functions",
    icon: "logos:azure-icon",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "aks",
    label: "Azure Kubernetes Service",
    icon: "logos:azure-icon",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "cloud-run",
    label: "Cloud Run",
    icon: "logos:google-cloud",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "durable-objects",
    label: "Cloudflare Durable Objects",
    icon: "logos:cloudflare",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "cloudflare-workers",
    label: "Cloudflare Workers",
    icon: "logos:cloudflare",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "gke",
    label: "Google Kubernetes Engine",
    icon: "logos:google-cloud",
    category: "compute",
    defaultType: "service",
  },
  {
    id: "netlify-functions",
    label: "Netlify Functions",
    icon: "logos:netlify",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "vercel-edge-functions",
    label: "Vercel Edge Functions",
    icon: "logos:vercel-icon",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "vercel-functions",
    label: "Vercel Functions",
    icon: "logos:vercel-icon",
    category: "compute",
    defaultType: "function",
  },
  {
    id: "airbyte",
    label: "Airbyte",
    icon: "logos:airbyte-icon",
    category: "data",
    defaultType: "etl",
  },
  {
    id: "redshift",
    label: "Amazon Redshift",
    icon: "logos:aws-redshift",
    category: "data",
    defaultType: "warehouse",
  },
  {
    id: "dagster",
    label: "Dagster",
    icon: "lucide:workflow",
    category: "data",
    defaultType: "orchestration",
  },
  {
    id: "databricks",
    label: "Databricks",
    icon: "logos:databricks",
    category: "data",
    defaultType: "warehouse",
  },
  {
    id: "dbt",
    label: "dbt",
    icon: "logos:dbt-icon",
    category: "data",
    defaultType: "etl",
  },
  {
    id: "drizzle",
    label: "Drizzle ORM",
    icon: "logos:drizzle",
    category: "data",
    defaultType: "service",
  },
  {
    id: "ent",
    label: "Ent",
    icon: "logos:go",
    category: "data",
    defaultType: "service",
  },
  {
    id: "fivetran",
    label: "Fivetran",
    icon: "lucide:git-pull-request-arrow",
    category: "data",
    defaultType: "etl",
  },
  {
    id: "gorm",
    label: "GORM",
    icon: "logos:go",
    category: "data",
    defaultType: "service",
  },
  {
    id: "mikroorm",
    label: "MikroORM",
    icon: "logos:npm-icon",
    category: "data",
    defaultType: "service",
  },
  {
    id: "mongoose",
    label: "Mongoose",
    icon: "logos:mongoose",
    category: "data",
    defaultType: "service",
  },
  {
    id: "motherduck",
    label: "MotherDuck",
    icon: "lucide:database",
    category: "data",
    defaultType: "warehouse",
  },
  {
    id: "prefect",
    label: "Prefect",
    icon: "lucide:workflow",
    category: "data",
    defaultType: "orchestration",
  },
  {
    id: "prisma",
    label: "Prisma",
    icon: "logos:prisma",
    category: "data",
    defaultType: "service",
  },
  {
    id: "sequelize",
    label: "Sequelize",
    icon: "logos:sequelize",
    category: "data",
    defaultType: "service",
  },
  {
    id: "sqlalchemy",
    label: "SQLAlchemy",
    icon: "logos:sqlalchemy",
    category: "data",
    defaultType: "service",
  },
  {
    id: "typeorm",
    label: "TypeORM",
    icon: "logos:typeorm",
    category: "data",
    defaultType: "service",
  },
  {
    id: "cassandra",
    label: "Apache Cassandra",
    icon: "logos:apache-cassandra",
    category: "database",
    defaultType: "database",
  },
  {
    id: "arangodb",
    label: "ArangoDB",
    icon: "logos:arangodb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "bigquery",
    label: "BigQuery",
    icon: "logos:google-bigquery",
    category: "database",
    defaultType: "database",
  },
  {
    id: "clickhouse",
    label: "ClickHouse",
    icon: "logos:clickhouse",
    category: "database",
    defaultType: "database",
  },
  {
    id: "firestore",
    label: "Cloud Firestore",
    icon: "logos:firebase",
    category: "database",
    defaultType: "database",
  },
  {
    id: "cloudflare-d1",
    label: "Cloudflare D1",
    icon: "logos:cloudflare",
    category: "database",
    defaultType: "database",
  },
  {
    id: "cloudflare-hyperdrive",
    label: "Cloudflare Hyperdrive",
    icon: "logos:cloudflare",
    category: "database",
    defaultType: "database",
  },
  {
    id: "cockroachdb",
    label: "CockroachDB",
    icon: "logos:cockroachdb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "convex",
    label: "Convex",
    icon: "logos:convex-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "couchbase",
    label: "Couchbase",
    icon: "logos:couchbase-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "couchdb",
    label: "CouchDB",
    icon: "logos:couchdb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "duckdb",
    label: "DuckDB",
    icon: "logos:duckdb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "dynamodb",
    label: "DynamoDB",
    icon: "logos:aws-dynamodb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "electric-sql",
    label: "ElectricSQL",
    icon: "lucide:zap",
    category: "database",
    defaultType: "database",
  },
  {
    id: "firebase",
    label: "Firebase",
    icon: "logos:firebase",
    category: "database",
    defaultType: "database",
  },
  {
    id: "firebase-realtime-db",
    label: "Firebase Realtime Database",
    icon: "logos:firebase",
    category: "database",
    defaultType: "database",
  },
  {
    id: "firebase-firestore",
    label: "Firestore",
    icon: "logos:firebase",
    category: "database",
    defaultType: "database",
  },
  {
    id: "influxdb",
    label: "InfluxDB",
    icon: "logos:influxdb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "instantdb",
    label: "InstantDB",
    icon: "lucide:database",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mariadb",
    label: "MariaDB",
    icon: "logos:mariadb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mongodb",
    label: "MongoDB",
    icon: "logos:mongodb-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "mysql",
    label: "MySQL",
    icon: "logos:mysql",
    category: "database",
    defaultType: "database",
  },
  {
    id: "neo4j",
    label: "Neo4j",
    icon: "logos:neo4j",
    category: "database",
    defaultType: "database",
  },
  {
    id: "neon",
    label: "Neon",
    icon: "logos:neon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "oracle",
    label: "Oracle",
    icon: "logos:oracle",
    category: "database",
    defaultType: "database",
  },
  {
    id: "oracle-db",
    label: "Oracle Database",
    icon: "logos:oracle",
    category: "database",
    defaultType: "database",
  },
  {
    id: "planetscale",
    label: "PlanetScale",
    icon: "logos:planetscale",
    category: "database",
    defaultType: "database",
  },
  {
    id: "postgres",
    label: "PostgreSQL",
    icon: "logos:postgresql",
    category: "database",
    defaultType: "database",
  },
  {
    id: "powersync",
    label: "PowerSync",
    icon: "lucide:refresh-cw",
    category: "database",
    defaultType: "database",
  },
  {
    id: "scylladb",
    label: "ScyllaDB",
    icon: "logos:scylladb",
    category: "database",
    defaultType: "database",
  },
  {
    id: "snowflake",
    label: "Snowflake",
    icon: "logos:snowflake-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "sqlserver",
    label: "SQL Server",
    icon: "logos:microsoft-sql-server",
    category: "database",
    defaultType: "database",
  },
  {
    id: "sqlite",
    label: "SQLite",
    icon: "logos:sqlite",
    category: "database",
    defaultType: "database",
  },
  {
    id: "supabase",
    label: "Supabase",
    icon: "logos:supabase-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "supabase-db",
    label: "Supabase Postgres",
    icon: "logos:supabase-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "timescaledb",
    label: "TimescaleDB",
    icon: "logos:timescale-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "turso",
    label: "Turso",
    icon: "logos:turso",
    category: "database",
    defaultType: "database",
  },
  {
    id: "upstash",
    label: "Upstash",
    icon: "logos:upstash-icon",
    category: "database",
    defaultType: "database",
  },
  {
    id: "zero-sync",
    label: "Zero",
    icon: "lucide:refresh-cw",
    category: "database",
    defaultType: "database",
  },
  {
    id: "electron",
    label: "Electron",
    icon: "logos:electron",
    category: "desktop",
    defaultType: "client",
  },
  {
    id: "tauri",
    label: "Tauri",
    icon: "logos:tauri",
    category: "desktop",
    defaultType: "client",
  },
  {
    id: "ansible",
    label: "Ansible",
    icon: "logos:ansible",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "apache",
    label: "Apache",
    icon: "logos:apache",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "backstage",
    label: "Backstage",
    icon: "logos:backstage-icon",
    category: "devops",
    defaultType: "idp",
  },
  {
    id: "consul",
    label: "Consul",
    icon: "logos:consul",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "dagger",
    label: "Dagger",
    icon: "logos:dagger-icon",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "docker",
    label: "Docker",
    icon: "logos:docker-icon",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "envoy",
    label: "Envoy",
    icon: "logos:envoy-icon",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "port",
    label: "GetPort",
    icon: "simple-icons:port",
    category: "devops",
    defaultType: "idp",
  },
  {
    id: "helm",
    label: "Helm",
    icon: "logos:helm",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "istio",
    label: "Istio",
    icon: "logos:istio",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "kong",
    label: "Kong",
    icon: "logos:kong",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "kubernetes",
    label: "Kubernetes",
    icon: "logos:kubernetes",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "linkerd",
    label: "Linkerd",
    icon: "logos:linkerd",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "nginx",
    label: "Nginx",
    icon: "logos:nginx",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "opentofu",
    label: "OpenTofu",
    icon: "logos:opentofu",
    category: "devops",
    defaultType: "service",
  },
  {
    id: "pulumi",
    label: "Pulumi",
    icon: "logos:pulumi-icon",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "terraform",
    label: "Terraform",
    icon: "logos:terraform-icon",
    category: "devops",
    defaultType: "cicd",
  },
  {
    id: "traefik",
    label: "Traefik",
    icon: "logos:traefik",
    category: "devops",
    defaultType: "gateway",
  },
  {
    id: "angular",
    label: "Angular",
    icon: "logos:angular-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "echarts",
    label: "Apache ECharts",
    icon: "logos:apache",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "apollo-client",
    label: "Apollo Client",
    icon: "logos:apollo",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "ark-ui",
    label: "Ark UI",
    icon: "lucide:component",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "astro",
    label: "Astro",
    icon: "logos:astro-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "blazor",
    label: "Blazor",
    icon: "logos:blazor",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "chakra-ui",
    label: "Chakra UI",
    icon: "logos:chakra-ui",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "d3",
    label: "D3.js",
    icon: "logos:d3",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "daisyui",
    label: "DaisyUI",
    icon: "lucide:flower",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "framer-motion",
    label: "Framer Motion",
    icon: "logos:framer",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "fresh",
    label: "Fresh",
    icon: "logos:deno",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "gsap",
    label: "GSAP",
    icon: "logos:greensock-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "htmx",
    label: "HTMX",
    icon: "logos:htmx-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "inertia",
    label: "Inertia.js",
    icon: "logos:vitejs",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "jotai",
    label: "Jotai",
    icon: "logos:jotai",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "kotlin",
    label: "Kotlin",
    icon: "logos:kotlin-icon",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "blade",
    label: "Laravel Blade",
    icon: "logos:laravel",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "livewire",
    label: "Livewire",
    icon: "logos:laravel",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "mantine",
    label: "Mantine",
    icon: "logos:mantine-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "mui",
    label: "Material UI",
    icon: "logos:material-ui",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "million",
    label: "Million.js",
    icon: "logos:million",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "motion",
    label: "Motion",
    icon: "logos:npm-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "nextjs",
    label: "Next.js",
    icon: "logos:nextjs-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "nuxt",
    label: "Nuxt",
    icon: "logos:nuxt-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "parcel",
    label: "Parcel",
    icon: "logos:parcel-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "plotly",
    label: "Plotly",
    icon: "logos:plotly",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "qwik",
    label: "Qwik",
    icon: "logos:builderio-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "radix-ui",
    label: "Radix UI",
    icon: "logos:radix-ui",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "react",
    label: "React",
    icon: "logos:react",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "react-hook-form",
    label: "React Hook Form",
    icon: "logos:react-hook-form",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "react-router",
    label: "React Router",
    icon: "logos:react-router",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "react-three-fiber",
    label: "React Three Fiber",
    icon: "logos:react",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "redux-toolkit",
    label: "Redux Toolkit",
    icon: "logos:redux",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "redwoodjs",
    label: "RedwoodJS",
    icon: "logos:redwoodjs",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "remix",
    label: "Remix",
    icon: "logos:remix-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "rspack",
    label: "Rspack",
    icon: "logos:rust",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "shadcn-ui",
    label: "shadcn/ui",
    icon: "logos:shadcn-ui",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "solidjs",
    label: "SolidJS",
    icon: "logos:solidjs-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "solid-start",
    label: "SolidStart",
    icon: "logos:solidjs-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "svelte",
    label: "Svelte",
    icon: "logos:svelte-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "sveltekit",
    label: "SvelteKit",
    icon: "logos:svelte-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "swift",
    label: "Swift",
    icon: "logos:swift",
    category: "frontend",
    defaultType: "client",
  },
  {
    id: "swr",
    label: "SWR",
    icon: "logos:vercel-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tailwindcss",
    label: "Tailwind CSS",
    icon: "logos:tailwindcss-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-form",
    label: "TanStack Form",
    icon: "lucide:form-input",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-query",
    label: "TanStack Query",
    icon: "logos:tanstack",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-router",
    label: "TanStack Router",
    icon: "lucide:route",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-start",
    label: "TanStack Start",
    icon: "logos:tanstack",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "tanstack-table",
    label: "TanStack Table",
    icon: "lucide:table",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "threejs",
    label: "Three.js",
    icon: "logos:threejs",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "urql",
    label: "urql",
    icon: "logos:graphql",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "valibot",
    label: "Valibot",
    icon: "logos:npm-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "valtio",
    label: "Valtio",
    icon: "logos:npm-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "vite",
    label: "Vite",
    icon: "logos:vitejs",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "vue",
    label: "Vue",
    icon: "logos:vue",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "webpack",
    label: "Webpack",
    icon: "logos:webpack",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "xyflow",
    label: "XYFlow / React Flow",
    icon: "logos:react",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "yup",
    label: "Yup",
    icon: "logos:npm-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "zod",
    label: "Zod",
    icon: "logos:zod",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "zustand",
    label: "Zustand",
    icon: "logos:npm-icon",
    category: "frontend",
    defaultType: "frontend",
  },
  {
    id: "gcp-app-engine",
    label: "App Engine",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "compute",
  },
  {
    id: "gcp-bigquery",
    label: "BigQuery",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-bigtable",
    label: "Cloud Bigtable",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-build",
    label: "Cloud Build",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "cicd",
  },
  {
    id: "gcp-cdn",
    label: "Cloud CDN",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-composer",
    label: "Cloud Composer",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-datafusion",
    label: "Cloud Data Fusion",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dataflow",
    label: "Cloud Dataflow",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dataproc",
    label: "Cloud Dataproc",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-dns",
    label: "Cloud DNS",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-endpoints",
    label: "Cloud Endpoints",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-filestore",
    label: "Cloud Filestore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "storage",
  },
  {
    id: "gcp-firestore",
    label: "Cloud Firestore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-functions",
    label: "Cloud Functions",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "function",
  },
  {
    id: "gcp-iam",
    label: "Cloud IAM",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "auth",
  },
  {
    id: "gcp-iot",
    label: "Cloud IoT",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-kms",
    label: "Cloud KMS",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "security",
  },
  {
    id: "gcp-load-balancing",
    label: "Cloud Load Balancing",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gateway",
  },
  {
    id: "gcp-logging",
    label: "Cloud Logging",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-memorystore",
    label: "Cloud Memorystore",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "cache",
  },
  {
    id: "gcp-monitoring",
    label: "Cloud Monitoring",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-nat",
    label: "Cloud NAT",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "gcp-pubsub",
    label: "Cloud Pub/Sub",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-run",
    label: "Cloud Run",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "compute",
  },
  {
    id: "gcp-scheduler",
    label: "Cloud Scheduler",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "automation",
  },
  {
    id: "gcp-spanner",
    label: "Cloud Spanner",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-speech",
    label: "Cloud Speech-to-Text",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-sql",
    label: "Cloud SQL",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "database",
  },
  {
    id: "gcp-storage",
    label: "Cloud Storage",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "storage",
  },
  {
    id: "gcp-tasks",
    label: "Cloud Tasks",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-tpu",
    label: "Cloud TPU",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-trace",
    label: "Cloud Trace",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "monitoring",
  },
  {
    id: "gcp-translate",
    label: "Cloud Translation",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-video",
    label: "Cloud Video",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-vision",
    label: "Cloud Vision",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "ai",
  },
  {
    id: "gcp-workflows",
    label: "Cloud Workflows",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "automation",
  },
  {
    id: "gcp-eventarc",
    label: "Eventarc",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "messaging",
  },
  {
    id: "gcp-secret-manager",
    label: "Secret Manager",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "security",
  },
  {
    id: "gcp-vpc",
    label: "VPC",
    icon: "logos:google-cloud",
    category: "gcp",
    defaultType: "gcp",
  },
  {
    id: "ably",
    label: "Ably",
    icon: "logos:ably",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "firebase-cloud-messaging",
    label: "FCM",
    icon: "logos:firebase",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "mailchimp",
    label: "Mailchimp",
    icon: "logos:mailchimp",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "mailgun",
    label: "Mailgun",
    icon: "logos:mailgun-icon",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "mqtt",
    label: "MQTT",
    icon: "logos:mqtt",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "onesignal",
    label: "OneSignal",
    icon: "logos:onesignal",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "postmark",
    label: "Postmark",
    icon: "logos:postmark",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "pubnub",
    label: "PubNub",
    icon: "logos:pubnub",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "pusher",
    label: "Pusher",
    icon: "logos:pusher",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "resend",
    label: "Resend",
    icon: "logos:resend-icon",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "sendgrid",
    label: "SendGrid",
    icon: "logos:sendgrid",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "socketio",
    label: "Socket.io",
    icon: "logos:socket.io",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "socket-io",
    label: "Socket.IO",
    icon: "logos:socket-io",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "twilio",
    label: "Twilio",
    icon: "logos:twilio-icon",
    category: "messaging",
    defaultType: "messaging",
  },
  {
    id: "capacitor",
    label: "Capacitor",
    icon: "logos:capacitorjs-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "expo",
    label: "Expo",
    icon: "logos:expo-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "expo-router",
    label: "Expo Router",
    icon: "logos:expo-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "flutter",
    label: "Flutter",
    icon: "logos:flutter",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "ionic",
    label: "Ionic",
    icon: "logos:ionic-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "jetpack-compose",
    label: "Jetpack Compose",
    icon: "logos:kotlin-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "kotlin-multiplatform",
    label: "Kotlin Multiplatform",
    icon: "logos:kotlin-icon",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "nativewind",
    label: "NativeWind",
    icon: "lucide:wind",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "react-native",
    label: "React Native",
    icon: "logos:react",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "swiftui",
    label: "SwiftUI",
    icon: "logos:swift",
    category: "mobile",
    defaultType: "client",
  },
  {
    id: "amplitude",
    label: "Amplitude",
    icon: "logos:amplitude-icon",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "braintrust",
    label: "Braintrust",
    icon: "logos:npm-icon",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "datadog",
    label: "Datadog",
    icon: "logos:datadog",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "dynatrace",
    label: "Dynatrace",
    icon: "logos:dynatrace",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "grafana",
    label: "Grafana",
    icon: "logos:grafana",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "honeycomb",
    label: "Honeycomb",
    icon: "logos:honeycomb",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "jaeger",
    label: "Jaeger",
    icon: "logos:jaeger",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "langfuse",
    label: "Langfuse",
    icon: "logos:langfuse",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "langsmith",
    label: "LangSmith",
    icon: "logos:langchain",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "loki",
    label: "Loki",
    icon: "logos:grafana",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "mixpanel",
    label: "Mixpanel",
    icon: "logos:mixpanel",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "newrelic",
    label: "New Relic",
    icon: "logos:new-relic",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "opentelemetry",
    label: "OpenTelemetry",
    icon: "logos:opentelemetry",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "posthog",
    label: "PostHog",
    icon: "logos:posthog",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "prometheus",
    label: "Prometheus",
    icon: "logos:prometheus",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "sentry",
    label: "Sentry",
    icon: "logos:sentry",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "splunk",
    label: "Splunk",
    icon: "logos:splunk",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "zipkin",
    label: "Zipkin",
    icon: "logos:zipkin",
    category: "monitoring",
    defaultType: "monitoring",
  },
  {
    id: "adyen",
    label: "Adyen",
    icon: "logos:adyen",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "affirm",
    label: "Affirm",
    icon: "logos:affirm",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "afterpay",
    label: "Afterpay",
    icon: "logos:afterpay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "alipay",
    label: "Alipay",
    icon: "logos:alipay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "amazon-pay",
    label: "Amazon Pay",
    icon: "logos:amazon-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "apple-pay",
    label: "Apple Pay",
    icon: "logos:apple-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "braintree",
    label: "Braintree",
    icon: "logos:braintree",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "google-pay",
    label: "Google Pay",
    icon: "logos:google-pay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "klarna",
    label: "Klarna",
    icon: "logos:klarna",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "lemon-squeezy",
    label: "Lemon Squeezy",
    icon: "logos:lemonsqueezy",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "mollie",
    label: "Mollie",
    icon: "logos:mollie",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "paddle",
    label: "Paddle",
    icon: "logos:paddle",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "paypal",
    label: "PayPal",
    icon: "logos:paypal",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "razorpay",
    label: "Razorpay",
    icon: "logos:razorpay",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "shopify-payments",
    label: "Shopify Payments",
    icon: "logos:shopify",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "square",
    label: "Square",
    icon: "logos:square",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "stripe",
    label: "Stripe",
    icon: "logos:stripe",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "wechat-pay",
    label: "WeChat Pay",
    icon: "logos:wechat",
    category: "payment",
    defaultType: "payment",
  },
  {
    id: "flink",
    label: "Apache Flink",
    icon: "logos:apache-flink",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "kafka",
    label: "Apache Kafka",
    icon: "logos:apache-kafka",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "pulsar",
    label: "Apache Pulsar",
    icon: "logos:apache",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "bullmq",
    label: "BullMQ",
    icon: "logos:bull",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "cloudflare-queues",
    label: "Cloudflare Queues",
    icon: "logos:cloudflare",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "graphile-worker",
    label: "Graphile Worker",
    icon: "logos:postgresql",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "hatchet",
    label: "Hatchet",
    icon: "lucide:workflow",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "inngest",
    label: "Inngest",
    icon: "logos:inngest",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "nats",
    label: "NATS",
    icon: "logos:nats-icon",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "qstash",
    label: "QStash",
    icon: "logos:upstash",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "rabbitmq",
    label: "RabbitMQ",
    icon: "logos:rabbitmq",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "redpanda",
    label: "Redpanda",
    icon: "logos:redpanda-icon",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "temporal",
    label: "Temporal",
    icon: "logos:temporal",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "trigger-dev",
    label: "Trigger.dev",
    icon: "logos:trigger-dev",
    category: "queue",
    defaultType: "queue",
  },
  {
    id: "algolia",
    label: "Algolia",
    icon: "logos:algolia",
    category: "search",
    defaultType: "service",
  },
  {
    id: "fathom",
    label: "Fathom",
    icon: "logos:fathom",
    category: "search",
    defaultType: "search",
  },
  {
    id: "fullstory",
    label: "FullStory",
    icon: "logos:fullstory",
    category: "search",
    defaultType: "search",
  },
  {
    id: "google-analytics",
    label: "Google Analytics",
    icon: "logos:google-analytics",
    category: "search",
    defaultType: "search",
  },
  {
    id: "heap",
    label: "Heap",
    icon: "logos:heap",
    category: "search",
    defaultType: "search",
  },
  {
    id: "hotjar",
    label: "Hotjar",
    icon: "logos:hotjar",
    category: "search",
    defaultType: "search",
  },
  {
    id: "logrocket",
    label: "LogRocket",
    icon: "logos:logrocket",
    category: "search",
    defaultType: "search",
  },
  {
    id: "meilisearch",
    label: "Meilisearch",
    icon: "logos:meilisearch",
    category: "search",
    defaultType: "service",
  },
  {
    id: "plausible",
    label: "Plausible",
    icon: "logos:plausible",
    category: "search",
    defaultType: "search",
  },
  {
    id: "segment",
    label: "Segment",
    icon: "logos:segment",
    category: "search",
    defaultType: "search",
  },
  {
    id: "tigris-search",
    label: "Tigris Search",
    icon: "lucide:search",
    category: "search",
    defaultType: "search",
  },
  {
    id: "typesense",
    label: "Typesense",
    icon: "logos:typesense",
    category: "search",
    defaultType: "service",
  },
  {
    id: "umami",
    label: "Umami",
    icon: "logos:umami",
    category: "search",
    defaultType: "search",
  },
  {
    id: "1password",
    label: "1Password",
    icon: "logos:1password",
    category: "security",
    defaultType: "security",
  },
  {
    id: "aikido",
    label: "Aikido Security",
    icon: "lucide:shield",
    category: "security",
    defaultType: "security",
  },
  {
    id: "arcjet",
    label: "Arcjet",
    icon: "lucide:shield",
    category: "security",
    defaultType: "security",
  },
  {
    id: "authy",
    label: "Authy",
    icon: "logos:authy",
    category: "security",
    defaultType: "security",
  },
  {
    id: "aws-waf",
    label: "AWS WAF",
    icon: "logos:aws",
    category: "security",
    defaultType: "security",
  },
  {
    id: "bitwarden",
    label: "Bitwarden",
    icon: "logos:bitwarden",
    category: "security",
    defaultType: "security",
  },
  {
    id: "burp-suite",
    label: "Burp Suite",
    icon: "logos:burp-suite",
    category: "security",
    defaultType: "security",
  },
  {
    id: "checkmarx",
    label: "Checkmarx",
    icon: "logos:checkmarx",
    category: "security",
    defaultType: "security",
  },
  {
    id: "cloudflare-waf",
    label: "Cloudflare WAF",
    icon: "logos:cloudflare",
    category: "security",
    defaultType: "security",
  },
  {
    id: "crowdstrike",
    label: "CrowdStrike",
    icon: "logos:crowdstrike",
    category: "security",
    defaultType: "security",
  },
  {
    id: "okta-security",
    label: "Okta Security",
    icon: "logos:okta",
    category: "security",
    defaultType: "security",
  },
  {
    id: "owasp-zap",
    label: "OWASP ZAP",
    icon: "logos:owasp",
    category: "security",
    defaultType: "security",
  },
  {
    id: "snyk",
    label: "Snyk",
    icon: "logos:snyk",
    category: "security",
    defaultType: "security",
  },
  {
    id: "socket-dev",
    label: "Socket",
    icon: "lucide:shield",
    category: "security",
    defaultType: "security",
  },
  {
    id: "sonarqube",
    label: "SonarQube",
    icon: "logos:sonarqube",
    category: "security",
    defaultType: "security",
  },
  {
    id: "trivy",
    label: "Trivy",
    icon: "logos:trivy",
    category: "security",
    defaultType: "security",
  },
  {
    id: "vault",
    label: "Vault",
    icon: "logos:vault",
    category: "security",
    defaultType: "security",
  },
  {
    id: "veracode",
    label: "Veracode",
    icon: "logos:veracode",
    category: "security",
    defaultType: "security",
  },
  {
    id: "s3",
    label: "Amazon S3",
    icon: "logos:aws-s3",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "aws-s3",
    label: "AWS S3",
    icon: "logos:amazon-s3",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "azure-blob",
    label: "Azure Blob Storage",
    icon: "logos:azure-icon",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "backblaze-b2",
    label: "Backblaze B2",
    icon: "logos:backblaze",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "backblaze",
    label: "Backblaze B2",
    icon: "logos:backblaze",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "box",
    label: "Box",
    icon: "logos:box",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "cloudflare-r2",
    label: "Cloudflare R2",
    icon: "logos:cloudflare",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "cloudinary",
    label: "Cloudinary",
    icon: "logos:cloudinary",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "dropbox",
    label: "Dropbox",
    icon: "logos:dropbox",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "gcs",
    label: "Google Cloud Storage",
    icon: "logos:google-cloud",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "imgix",
    label: "Imgix",
    icon: "logos:imgix",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "minio",
    label: "MinIO",
    icon: "logos:minio",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "supabase-storage",
    label: "Supabase Storage",
    icon: "logos:supabase-icon",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "uploadthing",
    label: "UploadThing",
    icon: "logos:uploadthing",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "wasabi",
    label: "Wasabi",
    icon: "logos:wasabi",
    category: "storage",
    defaultType: "storage",
  },
  {
    id: "appium",
    label: "Appium",
    icon: "logos:appium",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "artillery",
    label: "Artillery",
    icon: "logos:artillery",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "chromatic",
    label: "Chromatic",
    icon: "logos:chromatic",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "cypress",
    label: "Cypress",
    icon: "logos:cypress-icon",
    category: "testing",
    defaultType: "service",
  },
  {
    id: "detox",
    label: "Detox",
    icon: "logos:detox",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "gatling",
    label: "Gatling",
    icon: "logos:gatling",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "jest",
    label: "Jest",
    icon: "logos:jest",
    category: "testing",
    defaultType: "service",
  },
  {
    id: "k6",
    label: "k6",
    icon: "logos:k6",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "locust",
    label: "Locust",
    icon: "logos:locust",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "mocha",
    label: "Mocha",
    icon: "logos:mocha",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "percy",
    label: "Percy",
    icon: "logos:percy",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "playwright",
    label: "Playwright",
    icon: "logos:playwright",
    category: "testing",
    defaultType: "service",
  },
  {
    id: "selenium",
    label: "Selenium",
    icon: "logos:selenium",
    category: "testing",
    defaultType: "testing",
  },
  {
    id: "storybook",
    label: "Storybook",
    icon: "logos:storybook-icon",
    category: "testing",
    defaultType: "service",
  },
  {
    id: "vitest",
    label: "Vitest",
    icon: "logos:vitest",
    category: "testing",
    defaultType: "service",
  },
  {
    id: "arktype",
    label: "ArkType",
    icon: "lucide:badge-check",
    category: "tooling",
    defaultType: "validation",
  },
  {
    id: "biome",
    label: "Biome",
    icon: "logos:biome",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "entgo",
    label: "Ent",
    icon: "logos:go",
    category: "tooling",
    defaultType: "orm",
  },
  {
    id: "eslint",
    label: "ESLint",
    icon: "logos:eslint",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "kysely",
    label: "Kysely",
    icon: "lucide:database",
    category: "tooling",
    defaultType: "orm",
  },
  {
    id: "liveblocks",
    label: "Liveblocks",
    icon: "logos:liveblocks-icon",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "npm",
    label: "npm",
    icon: "logos:npm-icon",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "nx",
    label: "Nx",
    icon: "logos:nx",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "openapi-typescript",
    label: "openapi-typescript",
    icon: "lucide:file-code",
    category: "tooling",
    defaultType: "api-client",
  },
  {
    id: "orval",
    label: "Orval",
    icon: "lucide:file-code",
    category: "tooling",
    defaultType: "api-client",
  },
  {
    id: "pgtyped",
    label: "pgtyped",
    icon: "lucide:database",
    category: "tooling",
    defaultType: "orm",
  },
  {
    id: "pnpm",
    label: "pnpm",
    icon: "logos:pnpm",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "prettier",
    label: "Prettier",
    icon: "logos:prettier",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "redocly",
    label: "Redocly",
    icon: "lucide:file-code",
    category: "tooling",
    defaultType: "api-docs",
  },
  {
    id: "scalar",
    label: "Scalar",
    icon: "lucide:file-code",
    category: "tooling",
    defaultType: "api-docs",
  },
  {
    id: "sqlc",
    label: "sqlc",
    icon: "lucide:database",
    category: "tooling",
    defaultType: "orm",
  },
  {
    id: "sqlc-gen-typescript",
    label: "sqlc-gen-typescript",
    icon: "lucide:database",
    category: "tooling",
    defaultType: "orm",
  },
  {
    id: "swagger",
    label: "Swagger",
    icon: "logos:swagger",
    category: "tooling",
    defaultType: "api-docs",
  },
  {
    id: "turborepo",
    label: "Turborepo",
    icon: "logos:turborepo-icon",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "yarn",
    label: "Yarn",
    icon: "logos:yarn",
    category: "tooling",
    defaultType: "service",
  },
  {
    id: "chroma",
    label: "Chroma",
    icon: "logos:chroma",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "cloudflare-vectorize",
    label: "Cloudflare Vectorize",
    icon: "logos:cloudflare",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "deeplake",
    label: "Deep Lake",
    icon: "logos:activeloop",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "elasticsearch",
    label: "Elasticsearch",
    icon: "logos:elasticsearch",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "faiss",
    label: "FAISS",
    icon: "logos:meta",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "lancedb",
    label: "LanceDB",
    icon: "logos:lancedb",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "milvus",
    label: "Milvus",
    icon: "logos:milvus-icon",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "opensearch",
    label: "OpenSearch",
    icon: "logos:opensearch",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "pgvector",
    label: "pgvector",
    icon: "logos:postgresql",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "pinecone",
    label: "Pinecone",
    icon: "logos:pinecone",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "qdrant",
    label: "Qdrant",
    icon: "logos:qdrant",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "redis-vector",
    label: "Redis Vector",
    icon: "logos:redis",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "vespa",
    label: "Vespa",
    icon: "logos:vespa",
    category: "vector-db",
    defaultType: "vector-db",
  },
  {
    id: "weaviate",
    label: "Weaviate",
    icon: "logos:weaviate",
    category: "vector-db",
    defaultType: "vector-db",
  },
];

export function getTechById(id: string): TechItem | undefined {
  return TECH_ECOSYSTEM.find((t) => t.id === id);
}

export function getTechsByCategory(category: TechCategory): TechItem[] {
  return TECH_ECOSYSTEM.filter((t) => t.category === category);
}

export function getTechsByType(defaultType: string): TechItem[] {
  return TECH_ECOSYSTEM.filter((t) => t.defaultType === defaultType);
}
